/**
 * This class is generated by jOOQ
 */
package assets.dietfix.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DietfixAnsRecord extends org.jooq.impl.UpdatableRecordImpl<assets.dietfix.tables.records.DietfixAnsRecord> implements org.jooq.Record4<java.lang.Integer, byte[], assets.dietfix.enums.DietfixAnsAnsexpert, java.lang.String> {

	private static final long serialVersionUID = 1462464803;

	/**
	 * Setter for <code>dietfix.dietfix_ans.AnsID</code>. 
	 */
	public void setAnsid(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>dietfix.dietfix_ans.AnsID</code>. 
	 */
	public java.lang.Integer getAnsid() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>dietfix.dietfix_ans.AnsObj</code>. 
	 */
	public void setAnsobj(byte[] value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>dietfix.dietfix_ans.AnsObj</code>. 
	 */
	public byte[] getAnsobj() {
		return (byte[]) getValue(1);
	}

	/**
	 * Setter for <code>dietfix.dietfix_ans.AnsExpert</code>. 
	 */
	public void setAnsexpert(assets.dietfix.enums.DietfixAnsAnsexpert value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>dietfix.dietfix_ans.AnsExpert</code>. 
	 */
	public assets.dietfix.enums.DietfixAnsAnsexpert getAnsexpert() {
		return (assets.dietfix.enums.DietfixAnsAnsexpert) getValue(2);
	}

	/**
	 * Setter for <code>dietfix.dietfix_ans.AnsDesc</code>. 
	 */
	public void setAnsdesc(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>dietfix.dietfix_ans.AnsDesc</code>. 
	 */
	public java.lang.String getAnsdesc() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, byte[], assets.dietfix.enums.DietfixAnsAnsexpert, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, byte[], assets.dietfix.enums.DietfixAnsAnsexpert, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return assets.dietfix.tables.DietfixAns.DIETFIX_ANS.ANSID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field2() {
		return assets.dietfix.tables.DietfixAns.DIETFIX_ANS.ANSOBJ;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<assets.dietfix.enums.DietfixAnsAnsexpert> field3() {
		return assets.dietfix.tables.DietfixAns.DIETFIX_ANS.ANSEXPERT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return assets.dietfix.tables.DietfixAns.DIETFIX_ANS.ANSDESC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getAnsid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value2() {
		return getAnsobj();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public assets.dietfix.enums.DietfixAnsAnsexpert value3() {
		return getAnsexpert();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getAnsdesc();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DietfixAnsRecord
	 */
	public DietfixAnsRecord() {
		super(assets.dietfix.tables.DietfixAns.DIETFIX_ANS);
	}
}
