/**
 * This class is generated by jOOQ
 */
package assets.dietfix.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KnownWordsRecord extends org.jooq.impl.UpdatableRecordImpl<assets.dietfix.tables.records.KnownWordsRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1313168302;

	/**
	 * Setter for <code>dietfix.known_words.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>dietfix.known_words.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>dietfix.known_words.word</code>. 
	 */
	public void setWord(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>dietfix.known_words.word</code>. 
	 */
	public java.lang.String getWord() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>dietfix.known_words.pos_tag</code>. 
	 */
	public void setPosTag(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>dietfix.known_words.pos_tag</code>. 
	 */
	public java.lang.String getPosTag() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return assets.dietfix.tables.KnownWords.KNOWN_WORDS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return assets.dietfix.tables.KnownWords.KNOWN_WORDS.WORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return assets.dietfix.tables.KnownWords.KNOWN_WORDS.POS_TAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getWord();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getPosTag();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached KnownWordsRecord
	 */
	public KnownWordsRecord() {
		super(assets.dietfix.tables.KnownWords.KNOWN_WORDS);
	}
}
