/**
 * This class is generated by jOOQ
 */
package assets.dietfix.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KwordActionsRecord extends org.jooq.impl.UpdatableRecordImpl<assets.dietfix.tables.records.KwordActionsRecord> implements org.jooq.Record2<java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = -2135628099;

	/**
	 * Setter for <code>dietfix.kword_actions.ActionID</code>. 
	 */
	public void setActionid(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>dietfix.kword_actions.ActionID</code>. 
	 */
	public java.lang.Integer getActionid() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>dietfix.kword_actions.KWordID</code>. 
	 */
	public void setKwordid(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>dietfix.kword_actions.KWordID</code>. 
	 */
	public java.lang.String getKwordid() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return assets.dietfix.tables.KwordActions.KWORD_ACTIONS.ACTIONID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return assets.dietfix.tables.KwordActions.KWORD_ACTIONS.KWORDID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getActionid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getKwordid();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached KwordActionsRecord
	 */
	public KwordActionsRecord() {
		super(assets.dietfix.tables.KwordActions.KWORD_ACTIONS);
	}
}
