/**
 * This class is generated by jOOQ
 */
package assets.dietfix.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserProfileRecord extends org.jooq.impl.UpdatableRecordImpl<assets.dietfix.tables.records.UserProfileRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 855396697;

	/**
	 * Setter for <code>dietfix.user_profile.profileID</code>. 
	 */
	public void setProfileid(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>dietfix.user_profile.profileID</code>. 
	 */
	public java.lang.Integer getProfileid() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>dietfix.user_profile.userID</code>. 
	 */
	public void setUserid(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>dietfix.user_profile.userID</code>. 
	 */
	public java.lang.Integer getUserid() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>dietfix.user_profile.historyBackgroundID</code>. 
	 */
	public void setHistorybackgroundid(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>dietfix.user_profile.historyBackgroundID</code>. 
	 */
	public java.lang.Integer getHistorybackgroundid() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return assets.dietfix.tables.UserProfile.USER_PROFILE.PROFILEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return assets.dietfix.tables.UserProfile.USER_PROFILE.USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return assets.dietfix.tables.UserProfile.USER_PROFILE.HISTORYBACKGROUNDID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getProfileid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getHistorybackgroundid();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserProfileRecord
	 */
	public UserProfileRecord() {
		super(assets.dietfix.tables.UserProfile.USER_PROFILE);
	}
}
