/**
 * This class is generated by jOOQ
 */
package assets.dietfix.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends org.jooq.impl.UpdatableRecordImpl<assets.dietfix.tables.records.UserRecord> implements org.jooq.Record9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Date, java.sql.Date> {

	private static final long serialVersionUID = -6525750;

	/**
	 * Setter for <code>dietfix.user.userID</code>. 
	 */
	public void setUserid(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>dietfix.user.userID</code>. 
	 */
	public java.lang.Integer getUserid() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>dietfix.user.username</code>. 
	 */
	public void setUsername(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>dietfix.user.username</code>. 
	 */
	public java.lang.String getUsername() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>dietfix.user.password</code>. 
	 */
	public void setPassword(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>dietfix.user.password</code>. 
	 */
	public java.lang.String getPassword() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>dietfix.user.salt</code>. 
	 */
	public void setSalt(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>dietfix.user.salt</code>. 
	 */
	public java.lang.String getSalt() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>dietfix.user.first_name</code>. 
	 */
	public void setFirstName(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>dietfix.user.first_name</code>. 
	 */
	public java.lang.String getFirstName() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>dietfix.user.middle_name</code>. 
	 */
	public void setMiddleName(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>dietfix.user.middle_name</code>. 
	 */
	public java.lang.String getMiddleName() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>dietfix.user.last_name</code>. 
	 */
	public void setLastName(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>dietfix.user.last_name</code>. 
	 */
	public java.lang.String getLastName() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>dietfix.user.date_created</code>. 
	 */
	public void setDateCreated(java.sql.Date value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>dietfix.user.date_created</code>. 
	 */
	public java.sql.Date getDateCreated() {
		return (java.sql.Date) getValue(7);
	}

	/**
	 * Setter for <code>dietfix.user.date_modified</code>. 
	 */
	public void setDateModified(java.sql.Date value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>dietfix.user.date_modified</code>. 
	 */
	public java.sql.Date getDateModified() {
		return (java.sql.Date) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Date, java.sql.Date> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Date, java.sql.Date> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return assets.dietfix.tables.User.USER.USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return assets.dietfix.tables.User.USER.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return assets.dietfix.tables.User.USER.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return assets.dietfix.tables.User.USER.SALT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return assets.dietfix.tables.User.USER.FIRST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return assets.dietfix.tables.User.USER.MIDDLE_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return assets.dietfix.tables.User.USER.LAST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field8() {
		return assets.dietfix.tables.User.USER.DATE_CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field9() {
		return assets.dietfix.tables.User.USER.DATE_MODIFIED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getSalt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getFirstName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getMiddleName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getLastName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value8() {
		return getDateCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value9() {
		return getDateModified();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserRecord
	 */
	public UserRecord() {
		super(assets.dietfix.tables.User.USER);
	}
}
