/**
 * This class is generated by jOOQ
 */
package assets.dietfix.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserHistoryRecord extends org.jooq.impl.UpdatableRecordImpl<assets.dietfix.tables.records.UserHistoryRecord> implements org.jooq.Record9<java.lang.Integer, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte> {

	private static final long serialVersionUID = -614987189;

	/**
	 * Setter for <code>dietfix.user_history.historyBackgroundID</code>. 
	 */
	public void setHistorybackgroundid(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>dietfix.user_history.historyBackgroundID</code>. 
	 */
	public java.lang.Integer getHistorybackgroundid() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>dietfix.user_history.hasAsthma</code>. 
	 */
	public void setHasasthma(java.lang.Byte value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>dietfix.user_history.hasAsthma</code>. 
	 */
	public java.lang.Byte getHasasthma() {
		return (java.lang.Byte) getValue(1);
	}

	/**
	 * Setter for <code>dietfix.user_history.hasDiebetes</code>. 
	 */
	public void setHasdiebetes(java.lang.Byte value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>dietfix.user_history.hasDiebetes</code>. 
	 */
	public java.lang.Byte getHasdiebetes() {
		return (java.lang.Byte) getValue(2);
	}

	/**
	 * Setter for <code>dietfix.user_history.hasSeaFoodAllergy</code>. 
	 */
	public void setHasseafoodallergy(java.lang.Byte value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>dietfix.user_history.hasSeaFoodAllergy</code>. 
	 */
	public java.lang.Byte getHasseafoodallergy() {
		return (java.lang.Byte) getValue(3);
	}

	/**
	 * Setter for <code>dietfix.user_history.hasChickenAllergy</code>. 
	 */
	public void setHaschickenallergy(java.lang.Byte value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>dietfix.user_history.hasChickenAllergy</code>. 
	 */
	public java.lang.Byte getHaschickenallergy() {
		return (java.lang.Byte) getValue(4);
	}

	/**
	 * Setter for <code>dietfix.user_history.hasPorkAllergy</code>. 
	 */
	public void setHasporkallergy(java.lang.Byte value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>dietfix.user_history.hasPorkAllergy</code>. 
	 */
	public java.lang.Byte getHasporkallergy() {
		return (java.lang.Byte) getValue(5);
	}

	/**
	 * Setter for <code>dietfix.user_history.hasVeggieAllergy</code>. 
	 */
	public void setHasveggieallergy(java.lang.Byte value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>dietfix.user_history.hasVeggieAllergy</code>. 
	 */
	public java.lang.Byte getHasveggieallergy() {
		return (java.lang.Byte) getValue(6);
	}

	/**
	 * Setter for <code>dietfix.user_history.hasAlcoholAllergy</code>. 
	 */
	public void setHasalcoholallergy(java.lang.Byte value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>dietfix.user_history.hasAlcoholAllergy</code>. 
	 */
	public java.lang.Byte getHasalcoholallergy() {
		return (java.lang.Byte) getValue(7);
	}

	/**
	 * Setter for <code>dietfix.user_history.hasHeartProblem</code>. 
	 */
	public void setHasheartproblem(java.lang.Byte value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>dietfix.user_history.hasHeartProblem</code>. 
	 */
	public java.lang.Byte getHasheartproblem() {
		return (java.lang.Byte) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return assets.dietfix.tables.UserHistory.USER_HISTORY.HISTORYBACKGROUNDID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field2() {
		return assets.dietfix.tables.UserHistory.USER_HISTORY.HASASTHMA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field3() {
		return assets.dietfix.tables.UserHistory.USER_HISTORY.HASDIEBETES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field4() {
		return assets.dietfix.tables.UserHistory.USER_HISTORY.HASSEAFOODALLERGY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field5() {
		return assets.dietfix.tables.UserHistory.USER_HISTORY.HASCHICKENALLERGY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field6() {
		return assets.dietfix.tables.UserHistory.USER_HISTORY.HASPORKALLERGY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field7() {
		return assets.dietfix.tables.UserHistory.USER_HISTORY.HASVEGGIEALLERGY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field8() {
		return assets.dietfix.tables.UserHistory.USER_HISTORY.HASALCOHOLALLERGY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field9() {
		return assets.dietfix.tables.UserHistory.USER_HISTORY.HASHEARTPROBLEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getHistorybackgroundid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value2() {
		return getHasasthma();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value3() {
		return getHasdiebetes();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value4() {
		return getHasseafoodallergy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value5() {
		return getHaschickenallergy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value6() {
		return getHasporkallergy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value7() {
		return getHasveggieallergy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value8() {
		return getHasalcoholallergy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value9() {
		return getHasheartproblem();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserHistoryRecord
	 */
	public UserHistoryRecord() {
		super(assets.dietfix.tables.UserHistory.USER_HISTORY);
	}
}
