/**
 * This class is generated by jOOQ
 */
package assets.dietfix;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dietfix extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1183889577;

	/**
	 * The singleton instance of <code>dietfix</code>
	 */
	public static final Dietfix DIETFIX = new Dietfix();

	/**
	 * No further instances allowed
	 */
	private Dietfix() {
		super("dietfix");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			assets.dietfix.tables.DietfixAns.DIETFIX_ANS,
			assets.dietfix.tables.KnownWords.KNOWN_WORDS,
			assets.dietfix.tables.KwordActions.KWORD_ACTIONS,
			assets.dietfix.tables.NoiseWords.NOISE_WORDS,
			assets.dietfix.tables.User.USER,
			assets.dietfix.tables.UserHistory.USER_HISTORY,
			assets.dietfix.tables.UserProfile.USER_PROFILE);
	}
}
