/**
 * This class is generated by jOOQ
 */
package assets.dietfix;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>dietfix</code> 
 * schema
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<assets.dietfix.tables.records.DietfixAnsRecord, java.lang.Integer> IDENTITY_DIETFIX_ANS = Identities0.IDENTITY_DIETFIX_ANS;
	public static final org.jooq.Identity<assets.dietfix.tables.records.KnownWordsRecord, java.lang.Integer> IDENTITY_KNOWN_WORDS = Identities0.IDENTITY_KNOWN_WORDS;
	public static final org.jooq.Identity<assets.dietfix.tables.records.KwordActionsRecord, java.lang.Integer> IDENTITY_KWORD_ACTIONS = Identities0.IDENTITY_KWORD_ACTIONS;
	public static final org.jooq.Identity<assets.dietfix.tables.records.NoiseWordsRecord, java.lang.Integer> IDENTITY_NOISE_WORDS = Identities0.IDENTITY_NOISE_WORDS;
	public static final org.jooq.Identity<assets.dietfix.tables.records.UserRecord, java.lang.Integer> IDENTITY_USER = Identities0.IDENTITY_USER;
	public static final org.jooq.Identity<assets.dietfix.tables.records.UserHistoryRecord, java.lang.Integer> IDENTITY_USER_HISTORY = Identities0.IDENTITY_USER_HISTORY;
	public static final org.jooq.Identity<assets.dietfix.tables.records.UserProfileRecord, java.lang.Integer> IDENTITY_USER_PROFILE = Identities0.IDENTITY_USER_PROFILE;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<assets.dietfix.tables.records.DietfixAnsRecord> KEY_DIETFIX_ANS_PRIMARY = UniqueKeys0.KEY_DIETFIX_ANS_PRIMARY;
	public static final org.jooq.UniqueKey<assets.dietfix.tables.records.KnownWordsRecord> KEY_KNOWN_WORDS_PRIMARY = UniqueKeys0.KEY_KNOWN_WORDS_PRIMARY;
	public static final org.jooq.UniqueKey<assets.dietfix.tables.records.KwordActionsRecord> KEY_KWORD_ACTIONS_PRIMARY = UniqueKeys0.KEY_KWORD_ACTIONS_PRIMARY;
	public static final org.jooq.UniqueKey<assets.dietfix.tables.records.NoiseWordsRecord> KEY_NOISE_WORDS_PRIMARY = UniqueKeys0.KEY_NOISE_WORDS_PRIMARY;
	public static final org.jooq.UniqueKey<assets.dietfix.tables.records.UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;
	public static final org.jooq.UniqueKey<assets.dietfix.tables.records.UserHistoryRecord> KEY_USER_HISTORY_PRIMARY = UniqueKeys0.KEY_USER_HISTORY_PRIMARY;
	public static final org.jooq.UniqueKey<assets.dietfix.tables.records.UserProfileRecord> KEY_USER_PROFILE_PRIMARY = UniqueKeys0.KEY_USER_PROFILE_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<assets.dietfix.tables.records.UserProfileRecord, assets.dietfix.tables.records.UserRecord> USER_PROFILE_IBFK_1 = ForeignKeys0.USER_PROFILE_IBFK_1;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<assets.dietfix.tables.records.DietfixAnsRecord, java.lang.Integer> IDENTITY_DIETFIX_ANS = createIdentity(assets.dietfix.tables.DietfixAns.DIETFIX_ANS, assets.dietfix.tables.DietfixAns.DIETFIX_ANS.ANSID);
		public static org.jooq.Identity<assets.dietfix.tables.records.KnownWordsRecord, java.lang.Integer> IDENTITY_KNOWN_WORDS = createIdentity(assets.dietfix.tables.KnownWords.KNOWN_WORDS, assets.dietfix.tables.KnownWords.KNOWN_WORDS.ID);
		public static org.jooq.Identity<assets.dietfix.tables.records.KwordActionsRecord, java.lang.Integer> IDENTITY_KWORD_ACTIONS = createIdentity(assets.dietfix.tables.KwordActions.KWORD_ACTIONS, assets.dietfix.tables.KwordActions.KWORD_ACTIONS.ACTIONID);
		public static org.jooq.Identity<assets.dietfix.tables.records.NoiseWordsRecord, java.lang.Integer> IDENTITY_NOISE_WORDS = createIdentity(assets.dietfix.tables.NoiseWords.NOISE_WORDS, assets.dietfix.tables.NoiseWords.NOISE_WORDS.ID);
		public static org.jooq.Identity<assets.dietfix.tables.records.UserRecord, java.lang.Integer> IDENTITY_USER = createIdentity(assets.dietfix.tables.User.USER, assets.dietfix.tables.User.USER.USERID);
		public static org.jooq.Identity<assets.dietfix.tables.records.UserHistoryRecord, java.lang.Integer> IDENTITY_USER_HISTORY = createIdentity(assets.dietfix.tables.UserHistory.USER_HISTORY, assets.dietfix.tables.UserHistory.USER_HISTORY.HISTORYBACKGROUNDID);
		public static org.jooq.Identity<assets.dietfix.tables.records.UserProfileRecord, java.lang.Integer> IDENTITY_USER_PROFILE = createIdentity(assets.dietfix.tables.UserProfile.USER_PROFILE, assets.dietfix.tables.UserProfile.USER_PROFILE.PROFILEID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<assets.dietfix.tables.records.DietfixAnsRecord> KEY_DIETFIX_ANS_PRIMARY = createUniqueKey(assets.dietfix.tables.DietfixAns.DIETFIX_ANS, assets.dietfix.tables.DietfixAns.DIETFIX_ANS.ANSID);
		public static final org.jooq.UniqueKey<assets.dietfix.tables.records.KnownWordsRecord> KEY_KNOWN_WORDS_PRIMARY = createUniqueKey(assets.dietfix.tables.KnownWords.KNOWN_WORDS, assets.dietfix.tables.KnownWords.KNOWN_WORDS.ID);
		public static final org.jooq.UniqueKey<assets.dietfix.tables.records.KwordActionsRecord> KEY_KWORD_ACTIONS_PRIMARY = createUniqueKey(assets.dietfix.tables.KwordActions.KWORD_ACTIONS, assets.dietfix.tables.KwordActions.KWORD_ACTIONS.ACTIONID);
		public static final org.jooq.UniqueKey<assets.dietfix.tables.records.NoiseWordsRecord> KEY_NOISE_WORDS_PRIMARY = createUniqueKey(assets.dietfix.tables.NoiseWords.NOISE_WORDS, assets.dietfix.tables.NoiseWords.NOISE_WORDS.ID);
		public static final org.jooq.UniqueKey<assets.dietfix.tables.records.UserRecord> KEY_USER_PRIMARY = createUniqueKey(assets.dietfix.tables.User.USER, assets.dietfix.tables.User.USER.USERID);
		public static final org.jooq.UniqueKey<assets.dietfix.tables.records.UserHistoryRecord> KEY_USER_HISTORY_PRIMARY = createUniqueKey(assets.dietfix.tables.UserHistory.USER_HISTORY, assets.dietfix.tables.UserHistory.USER_HISTORY.HISTORYBACKGROUNDID);
		public static final org.jooq.UniqueKey<assets.dietfix.tables.records.UserProfileRecord> KEY_USER_PROFILE_PRIMARY = createUniqueKey(assets.dietfix.tables.UserProfile.USER_PROFILE, assets.dietfix.tables.UserProfile.USER_PROFILE.PROFILEID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<assets.dietfix.tables.records.UserProfileRecord, assets.dietfix.tables.records.UserRecord> USER_PROFILE_IBFK_1 = createForeignKey(assets.dietfix.Keys.KEY_USER_PRIMARY, assets.dietfix.tables.UserProfile.USER_PROFILE, assets.dietfix.tables.UserProfile.USER_PROFILE.USERID);
	}
}
