/**
 * This class is generated by jOOQ
 */
package assets.dietfix;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in dietfix
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table dietfix.dietfix_ans
	 */
	public static final assets.dietfix.tables.DietfixAns DIETFIX_ANS = assets.dietfix.tables.DietfixAns.DIETFIX_ANS;

	/**
	 * The table dietfix.known_words
	 */
	public static final assets.dietfix.tables.KnownWords KNOWN_WORDS = assets.dietfix.tables.KnownWords.KNOWN_WORDS;

	/**
	 * The table dietfix.kword_actions
	 */
	public static final assets.dietfix.tables.KwordActions KWORD_ACTIONS = assets.dietfix.tables.KwordActions.KWORD_ACTIONS;

	/**
	 * The table dietfix.noise_words
	 */
	public static final assets.dietfix.tables.NoiseWords NOISE_WORDS = assets.dietfix.tables.NoiseWords.NOISE_WORDS;

	/**
	 * The table dietfix.user
	 */
	public static final assets.dietfix.tables.User USER = assets.dietfix.tables.User.USER;

	/**
	 * The table dietfix.user_history
	 */
	public static final assets.dietfix.tables.UserHistory USER_HISTORY = assets.dietfix.tables.UserHistory.USER_HISTORY;

	/**
	 * The table dietfix.user_profile
	 */
	public static final assets.dietfix.tables.UserProfile USER_PROFILE = assets.dietfix.tables.UserProfile.USER_PROFILE;
}
