/**
 * This class is generated by jOOQ
 */
package assets.sr25food.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AbbrevRecord extends org.jooq.impl.UpdatableRecordImpl<assets.sr25food.tables.records.AbbrevRecord> {

	private static final long serialVersionUID = 1833622026;

	/**
	 * Setter for <code>sr25food.abbrev.NDB_No</code>. 
	 */
	public void setNdbNo(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.NDB_No</code>. 
	 */
	public java.lang.String getNdbNo() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Shrt_Desc</code>. 
	 */
	public void setShrtDesc(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Shrt_Desc</code>. 
	 */
	public java.lang.String getShrtDesc() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Water_(g)</code>. 
	 */
	public void setWater_G(java.lang.Double value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Water_(g)</code>. 
	 */
	public java.lang.Double getWater_G() {
		return (java.lang.Double) getValue(2);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Energ_Kcal</code>. 
	 */
	public void setEnergKcal(java.lang.Double value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Energ_Kcal</code>. 
	 */
	public java.lang.Double getEnergKcal() {
		return (java.lang.Double) getValue(3);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Protein_(g)</code>. 
	 */
	public void setProtein_G(java.lang.Double value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Protein_(g)</code>. 
	 */
	public java.lang.Double getProtein_G() {
		return (java.lang.Double) getValue(4);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Lipid_Tot_(g)</code>. 
	 */
	public void setLipidTot_G(java.lang.Double value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Lipid_Tot_(g)</code>. 
	 */
	public java.lang.Double getLipidTot_G() {
		return (java.lang.Double) getValue(5);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Ash_(g)</code>. 
	 */
	public void setAsh_G(java.lang.Double value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Ash_(g)</code>. 
	 */
	public java.lang.Double getAsh_G() {
		return (java.lang.Double) getValue(6);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Carbohydrt_(g)</code>. 
	 */
	public void setCarbohydrt_G(java.lang.Double value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Carbohydrt_(g)</code>. 
	 */
	public java.lang.Double getCarbohydrt_G() {
		return (java.lang.Double) getValue(7);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Fiber_TD_(g)</code>. 
	 */
	public void setFiberTd_G(java.lang.Double value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Fiber_TD_(g)</code>. 
	 */
	public java.lang.Double getFiberTd_G() {
		return (java.lang.Double) getValue(8);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Sugar_Tot_(g)</code>. 
	 */
	public void setSugarTot_G(java.lang.Double value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Sugar_Tot_(g)</code>. 
	 */
	public java.lang.Double getSugarTot_G() {
		return (java.lang.Double) getValue(9);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Calcium_(mg)</code>. 
	 */
	public void setCalcium_Mg(java.lang.Double value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Calcium_(mg)</code>. 
	 */
	public java.lang.Double getCalcium_Mg() {
		return (java.lang.Double) getValue(10);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Iron_(mg)</code>. 
	 */
	public void setIron_Mg(java.lang.Double value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Iron_(mg)</code>. 
	 */
	public java.lang.Double getIron_Mg() {
		return (java.lang.Double) getValue(11);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Magnesium_(mg)</code>. 
	 */
	public void setMagnesium_Mg(java.lang.Double value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Magnesium_(mg)</code>. 
	 */
	public java.lang.Double getMagnesium_Mg() {
		return (java.lang.Double) getValue(12);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Phosphorus_(mg)</code>. 
	 */
	public void setPhosphorus_Mg(java.lang.Double value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Phosphorus_(mg)</code>. 
	 */
	public java.lang.Double getPhosphorus_Mg() {
		return (java.lang.Double) getValue(13);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Potassium_(mg)</code>. 
	 */
	public void setPotassium_Mg(java.lang.Double value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Potassium_(mg)</code>. 
	 */
	public java.lang.Double getPotassium_Mg() {
		return (java.lang.Double) getValue(14);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Sodium_(mg)</code>. 
	 */
	public void setSodium_Mg(java.lang.Double value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Sodium_(mg)</code>. 
	 */
	public java.lang.Double getSodium_Mg() {
		return (java.lang.Double) getValue(15);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Zinc_(mg)</code>. 
	 */
	public void setZinc_Mg(java.lang.Double value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Zinc_(mg)</code>. 
	 */
	public java.lang.Double getZinc_Mg() {
		return (java.lang.Double) getValue(16);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Copper_mg)</code>. 
	 */
	public void setCopperMg(java.lang.Double value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Copper_mg)</code>. 
	 */
	public java.lang.Double getCopperMg() {
		return (java.lang.Double) getValue(17);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Manganese_(mg)</code>. 
	 */
	public void setManganese_Mg(java.lang.Double value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Manganese_(mg)</code>. 
	 */
	public java.lang.Double getManganese_Mg() {
		return (java.lang.Double) getValue(18);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Selenium_(ug)</code>. 
	 */
	public void setSelenium_Ug(java.lang.Double value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Selenium_(ug)</code>. 
	 */
	public java.lang.Double getSelenium_Ug() {
		return (java.lang.Double) getValue(19);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Vit_C_(mg)</code>. 
	 */
	public void setVitC_Mg(java.lang.Double value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Vit_C_(mg)</code>. 
	 */
	public java.lang.Double getVitC_Mg() {
		return (java.lang.Double) getValue(20);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Thiamin_(mg)</code>. 
	 */
	public void setThiamin_Mg(java.lang.Double value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Thiamin_(mg)</code>. 
	 */
	public java.lang.Double getThiamin_Mg() {
		return (java.lang.Double) getValue(21);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Riboflavin_(mg)</code>. 
	 */
	public void setRiboflavin_Mg(java.lang.Double value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Riboflavin_(mg)</code>. 
	 */
	public java.lang.Double getRiboflavin_Mg() {
		return (java.lang.Double) getValue(22);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Niacin_(mg)</code>. 
	 */
	public void setNiacin_Mg(java.lang.Double value) {
		setValue(23, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Niacin_(mg)</code>. 
	 */
	public java.lang.Double getNiacin_Mg() {
		return (java.lang.Double) getValue(23);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Panto_Acid_mg)</code>. 
	 */
	public void setPantoAcidMg(java.lang.Double value) {
		setValue(24, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Panto_Acid_mg)</code>. 
	 */
	public java.lang.Double getPantoAcidMg() {
		return (java.lang.Double) getValue(24);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Vit_B6_(mg)</code>. 
	 */
	public void setVitB6_Mg(java.lang.Double value) {
		setValue(25, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Vit_B6_(mg)</code>. 
	 */
	public java.lang.Double getVitB6_Mg() {
		return (java.lang.Double) getValue(25);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Folate_Tot_(ug)</code>. 
	 */
	public void setFolateTot_Ug(java.lang.Double value) {
		setValue(26, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Folate_Tot_(ug)</code>. 
	 */
	public java.lang.Double getFolateTot_Ug() {
		return (java.lang.Double) getValue(26);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Folic_Acid_(ug)</code>. 
	 */
	public void setFolicAcid_Ug(java.lang.Double value) {
		setValue(27, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Folic_Acid_(ug)</code>. 
	 */
	public java.lang.Double getFolicAcid_Ug() {
		return (java.lang.Double) getValue(27);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Food_Folate_(ug)</code>. 
	 */
	public void setFoodFolate_Ug(java.lang.Double value) {
		setValue(28, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Food_Folate_(ug)</code>. 
	 */
	public java.lang.Double getFoodFolate_Ug() {
		return (java.lang.Double) getValue(28);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Folate_DFE_(ug)</code>. 
	 */
	public void setFolateDfe_Ug(java.lang.Double value) {
		setValue(29, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Folate_DFE_(ug)</code>. 
	 */
	public java.lang.Double getFolateDfe_Ug() {
		return (java.lang.Double) getValue(29);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Choline_Tot_ (mg)</code>. 
	 */
	public void setCholineTot__Mg(java.lang.Double value) {
		setValue(30, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Choline_Tot_ (mg)</code>. 
	 */
	public java.lang.Double getCholineTot__Mg() {
		return (java.lang.Double) getValue(30);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Vit_B12_(ug)</code>. 
	 */
	public void setVitB12_Ug(java.lang.Double value) {
		setValue(31, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Vit_B12_(ug)</code>. 
	 */
	public java.lang.Double getVitB12_Ug() {
		return (java.lang.Double) getValue(31);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Vit_A_IU</code>. 
	 */
	public void setVitAIu(java.lang.Double value) {
		setValue(32, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Vit_A_IU</code>. 
	 */
	public java.lang.Double getVitAIu() {
		return (java.lang.Double) getValue(32);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Vit_A_RAE</code>. 
	 */
	public void setVitARae(java.lang.Double value) {
		setValue(33, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Vit_A_RAE</code>. 
	 */
	public java.lang.Double getVitARae() {
		return (java.lang.Double) getValue(33);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Retinol_(ug)</code>. 
	 */
	public void setRetinol_Ug(java.lang.Double value) {
		setValue(34, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Retinol_(ug)</code>. 
	 */
	public java.lang.Double getRetinol_Ug() {
		return (java.lang.Double) getValue(34);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Alpha_Carot_(ug)</code>. 
	 */
	public void setAlphaCarot_Ug(java.lang.Double value) {
		setValue(35, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Alpha_Carot_(ug)</code>. 
	 */
	public java.lang.Double getAlphaCarot_Ug() {
		return (java.lang.Double) getValue(35);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Beta_Carot_(ug)</code>. 
	 */
	public void setBetaCarot_Ug(java.lang.Double value) {
		setValue(36, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Beta_Carot_(ug)</code>. 
	 */
	public java.lang.Double getBetaCarot_Ug() {
		return (java.lang.Double) getValue(36);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Beta_Crypt_(ug)</code>. 
	 */
	public void setBetaCrypt_Ug(java.lang.Double value) {
		setValue(37, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Beta_Crypt_(ug)</code>. 
	 */
	public java.lang.Double getBetaCrypt_Ug() {
		return (java.lang.Double) getValue(37);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Lycopene_(ug)</code>. 
	 */
	public void setLycopene_Ug(java.lang.Double value) {
		setValue(38, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Lycopene_(ug)</code>. 
	 */
	public java.lang.Double getLycopene_Ug() {
		return (java.lang.Double) getValue(38);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Lut+Zea_ (ug)</code>. 
	 */
	public void setLutZea__Ug(java.lang.Double value) {
		setValue(39, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Lut+Zea_ (ug)</code>. 
	 */
	public java.lang.Double getLutZea__Ug() {
		return (java.lang.Double) getValue(39);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Vit_E_(mg)</code>. 
	 */
	public void setVitE_Mg(java.lang.Double value) {
		setValue(40, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Vit_E_(mg)</code>. 
	 */
	public java.lang.Double getVitE_Mg() {
		return (java.lang.Double) getValue(40);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Vit_D_ (ug)</code>. 
	 */
	public void setVitD__Ug(java.lang.Double value) {
		setValue(41, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Vit_D_ (ug)</code>. 
	 */
	public java.lang.Double getVitD__Ug() {
		return (java.lang.Double) getValue(41);
	}

	/**
	 * Setter for <code>sr25food.abbrev.ViVit_D_IU</code>. 
	 */
	public void setVivitDIu(java.lang.Double value) {
		setValue(42, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.ViVit_D_IU</code>. 
	 */
	public java.lang.Double getVivitDIu() {
		return (java.lang.Double) getValue(42);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Vit_K_ (ug)</code>. 
	 */
	public void setVitK__Ug(java.lang.Double value) {
		setValue(43, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Vit_K_ (ug)</code>. 
	 */
	public java.lang.Double getVitK__Ug() {
		return (java.lang.Double) getValue(43);
	}

	/**
	 * Setter for <code>sr25food.abbrev.FA_Sat_(g)</code>. 
	 */
	public void setFaSat_G(java.lang.Double value) {
		setValue(44, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.FA_Sat_(g)</code>. 
	 */
	public java.lang.Double getFaSat_G() {
		return (java.lang.Double) getValue(44);
	}

	/**
	 * Setter for <code>sr25food.abbrev.FA_Mono_(g)</code>. 
	 */
	public void setFaMono_G(java.lang.Double value) {
		setValue(45, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.FA_Mono_(g)</code>. 
	 */
	public java.lang.Double getFaMono_G() {
		return (java.lang.Double) getValue(45);
	}

	/**
	 * Setter for <code>sr25food.abbrev.FA_Poly_(g)</code>. 
	 */
	public void setFaPoly_G(java.lang.Double value) {
		setValue(46, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.FA_Poly_(g)</code>. 
	 */
	public java.lang.Double getFaPoly_G() {
		return (java.lang.Double) getValue(46);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Cholestrl_(mg)</code>. 
	 */
	public void setCholestrl_Mg(java.lang.Double value) {
		setValue(47, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Cholestrl_(mg)</code>. 
	 */
	public java.lang.Double getCholestrl_Mg() {
		return (java.lang.Double) getValue(47);
	}

	/**
	 * Setter for <code>sr25food.abbrev.GmWt_1</code>. 
	 */
	public void setGmwt_1(java.lang.Double value) {
		setValue(48, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.GmWt_1</code>. 
	 */
	public java.lang.Double getGmwt_1() {
		return (java.lang.Double) getValue(48);
	}

	/**
	 * Setter for <code>sr25food.abbrev.GmWt_Desc1</code>. 
	 */
	public void setGmwtDesc1(java.lang.String value) {
		setValue(49, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.GmWt_Desc1</code>. 
	 */
	public java.lang.String getGmwtDesc1() {
		return (java.lang.String) getValue(49);
	}

	/**
	 * Setter for <code>sr25food.abbrev.GmWt_2</code>. 
	 */
	public void setGmwt_2(java.lang.Double value) {
		setValue(50, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.GmWt_2</code>. 
	 */
	public java.lang.Double getGmwt_2() {
		return (java.lang.Double) getValue(50);
	}

	/**
	 * Setter for <code>sr25food.abbrev.GmWt_Desc2</code>. 
	 */
	public void setGmwtDesc2(java.lang.String value) {
		setValue(51, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.GmWt_Desc2</code>. 
	 */
	public java.lang.String getGmwtDesc2() {
		return (java.lang.String) getValue(51);
	}

	/**
	 * Setter for <code>sr25food.abbrev.Refuse_Pct</code>. 
	 */
	public void setRefusePct(java.lang.Double value) {
		setValue(52, value);
	}

	/**
	 * Getter for <code>sr25food.abbrev.Refuse_Pct</code>. 
	 */
	public java.lang.Double getRefusePct() {
		return (java.lang.Double) getValue(52);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AbbrevRecord
	 */
	public AbbrevRecord() {
		super(assets.sr25food.tables.Abbrev.ABBREV);
	}
}
