/**
 * This class is generated by jOOQ
 */
package assets.sr25food.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * VIEW
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AllfoodsummaryRecord extends org.jooq.impl.TableRecordImpl<assets.sr25food.tables.records.AllfoodsummaryRecord> implements org.jooq.Record {

	private static final long serialVersionUID = -1784858173;

	// -------------------------------------------------------------------------
	// Record0 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row fieldsRow() {
		return (org.jooq.Row) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row valuesRow() {
		return (org.jooq.Row) super.valuesRow();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AllfoodsummaryRecord
	 */
	public AllfoodsummaryRecord() {
		super(assets.sr25food.tables.Allfoodsummary.ALLFOODSUMMARY);
	}
}
