/**
 * This class is generated by jOOQ
 */
package assets.sr25food.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataSrcRecord extends org.jooq.impl.UpdatableRecordImpl<assets.sr25food.tables.records.DataSrcRecord> implements org.jooq.Record9<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -971063013;

	/**
	 * Setter for <code>sr25food.data_src.DataSrc_ID</code>. 
	 */
	public void setDatasrcId(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sr25food.data_src.DataSrc_ID</code>. 
	 */
	public java.lang.String getDatasrcId() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>sr25food.data_src.Authors</code>. 
	 */
	public void setAuthors(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sr25food.data_src.Authors</code>. 
	 */
	public java.lang.String getAuthors() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>sr25food.data_src.Title</code>. 
	 */
	public void setTitle(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sr25food.data_src.Title</code>. 
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>sr25food.data_src.Year</code>. 
	 */
	public void setYear(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>sr25food.data_src.Year</code>. 
	 */
	public java.lang.String getYear() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>sr25food.data_src.Journal</code>. 
	 */
	public void setJournal(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>sr25food.data_src.Journal</code>. 
	 */
	public java.lang.String getJournal() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>sr25food.data_src.Vol_City</code>. 
	 */
	public void setVolCity(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>sr25food.data_src.Vol_City</code>. 
	 */
	public java.lang.String getVolCity() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>sr25food.data_src.Issue_State</code>. 
	 */
	public void setIssueState(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>sr25food.data_src.Issue_State</code>. 
	 */
	public java.lang.String getIssueState() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>sr25food.data_src.Start_Page</code>. 
	 */
	public void setStartPage(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>sr25food.data_src.Start_Page</code>. 
	 */
	public java.lang.String getStartPage() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>sr25food.data_src.End_Page</code>. 
	 */
	public void setEndPage(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>sr25food.data_src.End_Page</code>. 
	 */
	public java.lang.String getEndPage() {
		return (java.lang.String) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return assets.sr25food.tables.DataSrc.DATA_SRC.DATASRC_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return assets.sr25food.tables.DataSrc.DATA_SRC.AUTHORS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return assets.sr25food.tables.DataSrc.DATA_SRC.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return assets.sr25food.tables.DataSrc.DATA_SRC.YEAR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return assets.sr25food.tables.DataSrc.DATA_SRC.JOURNAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return assets.sr25food.tables.DataSrc.DATA_SRC.VOL_CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return assets.sr25food.tables.DataSrc.DATA_SRC.ISSUE_STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return assets.sr25food.tables.DataSrc.DATA_SRC.START_PAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return assets.sr25food.tables.DataSrc.DATA_SRC.END_PAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getDatasrcId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getAuthors();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getYear();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getJournal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getVolCity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getIssueState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getStartPage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getEndPage();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DataSrcRecord
	 */
	public DataSrcRecord() {
		super(assets.sr25food.tables.DataSrc.DATA_SRC);
	}
}
