/**
 * This class is generated by jOOQ
 */
package assets.sr25food.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatsrclnRecord extends org.jooq.impl.UpdatableRecordImpl<assets.sr25food.tables.records.DatsrclnRecord> implements org.jooq.Record3<java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1534633829;

	/**
	 * Setter for <code>sr25food.datsrcln.NDB_No</code>. 
	 */
	public void setNdbNo(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sr25food.datsrcln.NDB_No</code>. 
	 */
	public java.lang.String getNdbNo() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>sr25food.datsrcln.Nutr_No</code>. 
	 */
	public void setNutrNo(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sr25food.datsrcln.Nutr_No</code>. 
	 */
	public java.lang.String getNutrNo() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>sr25food.datsrcln.DataSrc_ID</code>. 
	 */
	public void setDatasrcId(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sr25food.datsrcln.DataSrc_ID</code>. 
	 */
	public java.lang.String getDatasrcId() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record3<java.lang.String, java.lang.String, java.lang.String> key() {
		return (org.jooq.Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return assets.sr25food.tables.Datsrcln.DATSRCLN.NDB_NO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return assets.sr25food.tables.Datsrcln.DATSRCLN.NUTR_NO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return assets.sr25food.tables.Datsrcln.DATSRCLN.DATASRC_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getNdbNo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getNutrNo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDatasrcId();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DatsrclnRecord
	 */
	public DatsrclnRecord() {
		super(assets.sr25food.tables.Datsrcln.DATSRCLN);
	}
}
