/**
 * This class is generated by jOOQ
 */
package assets.sr25food.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FoodDesRecord extends org.jooq.impl.UpdatableRecordImpl<assets.sr25food.tables.records.FoodDesRecord> implements org.jooq.Record14<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double> {

	private static final long serialVersionUID = 943147590;

	/**
	 * Setter for <code>sr25food.food_des.NDB_No</code>. 
	 */
	public void setNdbNo(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sr25food.food_des.NDB_No</code>. 
	 */
	public java.lang.String getNdbNo() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>sr25food.food_des.FdGrp_Cd</code>. 
	 */
	public void setFdgrpCd(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sr25food.food_des.FdGrp_Cd</code>. 
	 */
	public java.lang.String getFdgrpCd() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>sr25food.food_des.Long_Desc</code>. 
	 */
	public void setLongDesc(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sr25food.food_des.Long_Desc</code>. 
	 */
	public java.lang.String getLongDesc() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>sr25food.food_des.Shrt_Desc</code>. 
	 */
	public void setShrtDesc(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>sr25food.food_des.Shrt_Desc</code>. 
	 */
	public java.lang.String getShrtDesc() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>sr25food.food_des.ComName</code>. 
	 */
	public void setComname(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>sr25food.food_des.ComName</code>. 
	 */
	public java.lang.String getComname() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>sr25food.food_des.ManufacName</code>. 
	 */
	public void setManufacname(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>sr25food.food_des.ManufacName</code>. 
	 */
	public java.lang.String getManufacname() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>sr25food.food_des.Survey</code>. 
	 */
	public void setSurvey(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>sr25food.food_des.Survey</code>. 
	 */
	public java.lang.String getSurvey() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>sr25food.food_des.Ref_Desc</code>. 
	 */
	public void setRefDesc(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>sr25food.food_des.Ref_Desc</code>. 
	 */
	public java.lang.String getRefDesc() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>sr25food.food_des.Refuse</code>. 
	 */
	public void setRefuse(java.lang.Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>sr25food.food_des.Refuse</code>. 
	 */
	public java.lang.Integer getRefuse() {
		return (java.lang.Integer) getValue(8);
	}

	/**
	 * Setter for <code>sr25food.food_des.SciName</code>. 
	 */
	public void setSciname(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>sr25food.food_des.SciName</code>. 
	 */
	public java.lang.String getSciname() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>sr25food.food_des.N_Factor</code>. 
	 */
	public void setNFactor(java.lang.Double value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>sr25food.food_des.N_Factor</code>. 
	 */
	public java.lang.Double getNFactor() {
		return (java.lang.Double) getValue(10);
	}

	/**
	 * Setter for <code>sr25food.food_des.Pro_Factor</code>. 
	 */
	public void setProFactor(java.lang.Double value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>sr25food.food_des.Pro_Factor</code>. 
	 */
	public java.lang.Double getProFactor() {
		return (java.lang.Double) getValue(11);
	}

	/**
	 * Setter for <code>sr25food.food_des.Fat_Factor</code>. 
	 */
	public void setFatFactor(java.lang.Double value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>sr25food.food_des.Fat_Factor</code>. 
	 */
	public java.lang.Double getFatFactor() {
		return (java.lang.Double) getValue(12);
	}

	/**
	 * Setter for <code>sr25food.food_des.CHO_Factor</code>. 
	 */
	public void setChoFactor(java.lang.Double value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>sr25food.food_des.CHO_Factor</code>. 
	 */
	public java.lang.Double getChoFactor() {
		return (java.lang.Double) getValue(13);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record14 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row14<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double> fieldsRow() {
		return (org.jooq.Row14) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row14<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double> valuesRow() {
		return (org.jooq.Row14) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return assets.sr25food.tables.FoodDes.FOOD_DES.NDB_NO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return assets.sr25food.tables.FoodDes.FOOD_DES.FDGRP_CD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return assets.sr25food.tables.FoodDes.FOOD_DES.LONG_DESC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return assets.sr25food.tables.FoodDes.FOOD_DES.SHRT_DESC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return assets.sr25food.tables.FoodDes.FOOD_DES.COMNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return assets.sr25food.tables.FoodDes.FOOD_DES.MANUFACNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return assets.sr25food.tables.FoodDes.FOOD_DES.SURVEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return assets.sr25food.tables.FoodDes.FOOD_DES.REF_DESC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field9() {
		return assets.sr25food.tables.FoodDes.FOOD_DES.REFUSE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return assets.sr25food.tables.FoodDes.FOOD_DES.SCINAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field11() {
		return assets.sr25food.tables.FoodDes.FOOD_DES.N_FACTOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field12() {
		return assets.sr25food.tables.FoodDes.FOOD_DES.PRO_FACTOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field13() {
		return assets.sr25food.tables.FoodDes.FOOD_DES.FAT_FACTOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field14() {
		return assets.sr25food.tables.FoodDes.FOOD_DES.CHO_FACTOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getNdbNo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getFdgrpCd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getLongDesc();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getShrtDesc();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getComname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getManufacname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getSurvey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getRefDesc();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value9() {
		return getRefuse();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getSciname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value11() {
		return getNFactor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value12() {
		return getProFactor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value13() {
		return getFatFactor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value14() {
		return getChoFactor();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FoodDesRecord
	 */
	public FoodDesRecord() {
		super(assets.sr25food.tables.FoodDes.FOOD_DES);
	}
}
