/**
 * This class is generated by jOOQ
 */
package assets.sr25food.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FootnoteRecord extends org.jooq.impl.TableRecordImpl<assets.sr25food.tables.records.FootnoteRecord> implements org.jooq.Record5<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 277400295;

	/**
	 * Setter for <code>sr25food.footnote.NDB_NO</code>. 
	 */
	public void setNdbNo(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sr25food.footnote.NDB_NO</code>. 
	 */
	public java.lang.String getNdbNo() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>sr25food.footnote.Footnt_No</code>. 
	 */
	public void setFootntNo(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sr25food.footnote.Footnt_No</code>. 
	 */
	public java.lang.String getFootntNo() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>sr25food.footnote.Footnot_Typ</code>. 
	 */
	public void setFootnotTyp(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sr25food.footnote.Footnot_Typ</code>. 
	 */
	public java.lang.String getFootnotTyp() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>sr25food.footnote.Nutr_No</code>. 
	 */
	public void setNutrNo(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>sr25food.footnote.Nutr_No</code>. 
	 */
	public java.lang.String getNutrNo() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>sr25food.footnote.Footnot_Txt</code>. 
	 */
	public void setFootnotTxt(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>sr25food.footnote.Footnot_Txt</code>. 
	 */
	public java.lang.String getFootnotTxt() {
		return (java.lang.String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return assets.sr25food.tables.Footnote.FOOTNOTE.NDB_NO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return assets.sr25food.tables.Footnote.FOOTNOTE.FOOTNT_NO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return assets.sr25food.tables.Footnote.FOOTNOTE.FOOTNOT_TYP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return assets.sr25food.tables.Footnote.FOOTNOTE.NUTR_NO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return assets.sr25food.tables.Footnote.FOOTNOTE.FOOTNOT_TXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getNdbNo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getFootntNo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getFootnotTyp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getNutrNo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getFootnotTxt();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FootnoteRecord
	 */
	public FootnoteRecord() {
		super(assets.sr25food.tables.Footnote.FOOTNOTE);
	}
}
