/**
 * This class is generated by jOOQ
 */
package assets.sr25food.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NutDataRecord extends org.jooq.impl.UpdatableRecordImpl<assets.sr25food.tables.records.NutDataRecord> implements org.jooq.Record17<java.lang.String, java.lang.String, java.lang.Double, java.lang.Integer, java.lang.Double, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1660418592;

	/**
	 * Setter for <code>sr25food.nut_data.NDB_No</code>. 
	 */
	public void setNdbNo(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sr25food.nut_data.NDB_No</code>. 
	 */
	public java.lang.String getNdbNo() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>sr25food.nut_data.Nutr_No</code>. 
	 */
	public void setNutrNo(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sr25food.nut_data.Nutr_No</code>. 
	 */
	public java.lang.String getNutrNo() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>sr25food.nut_data.Nutr_Val</code>. 
	 */
	public void setNutrVal(java.lang.Double value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sr25food.nut_data.Nutr_Val</code>. 
	 */
	public java.lang.Double getNutrVal() {
		return (java.lang.Double) getValue(2);
	}

	/**
	 * Setter for <code>sr25food.nut_data.Num_Data_Pts</code>. 
	 */
	public void setNumDataPts(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>sr25food.nut_data.Num_Data_Pts</code>. 
	 */
	public java.lang.Integer getNumDataPts() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>sr25food.nut_data.Std_Error</code>. 
	 */
	public void setStdError(java.lang.Double value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>sr25food.nut_data.Std_Error</code>. 
	 */
	public java.lang.Double getStdError() {
		return (java.lang.Double) getValue(4);
	}

	/**
	 * Setter for <code>sr25food.nut_data.Src_Cd</code>. 
	 */
	public void setSrcCd(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>sr25food.nut_data.Src_Cd</code>. 
	 */
	public java.lang.String getSrcCd() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>sr25food.nut_data.Deriv_Cd</code>. 
	 */
	public void setDerivCd(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>sr25food.nut_data.Deriv_Cd</code>. 
	 */
	public java.lang.String getDerivCd() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>sr25food.nut_data.Ref_NDB_No</code>. 
	 */
	public void setRefNdbNo(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>sr25food.nut_data.Ref_NDB_No</code>. 
	 */
	public java.lang.String getRefNdbNo() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>sr25food.nut_data.Add_Nutr_Mark</code>. 
	 */
	public void setAddNutrMark(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>sr25food.nut_data.Add_Nutr_Mark</code>. 
	 */
	public java.lang.String getAddNutrMark() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>sr25food.nut_data.Num_Studies</code>. 
	 */
	public void setNumStudies(java.lang.Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>sr25food.nut_data.Num_Studies</code>. 
	 */
	public java.lang.Integer getNumStudies() {
		return (java.lang.Integer) getValue(9);
	}

	/**
	 * Setter for <code>sr25food.nut_data.Min</code>. 
	 */
	public void setMin(java.lang.Double value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>sr25food.nut_data.Min</code>. 
	 */
	public java.lang.Double getMin() {
		return (java.lang.Double) getValue(10);
	}

	/**
	 * Setter for <code>sr25food.nut_data.Max</code>. 
	 */
	public void setMax(java.lang.Double value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>sr25food.nut_data.Max</code>. 
	 */
	public java.lang.Double getMax() {
		return (java.lang.Double) getValue(11);
	}

	/**
	 * Setter for <code>sr25food.nut_data.DF</code>. 
	 */
	public void setDf(java.lang.Double value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>sr25food.nut_data.DF</code>. 
	 */
	public java.lang.Double getDf() {
		return (java.lang.Double) getValue(12);
	}

	/**
	 * Setter for <code>sr25food.nut_data.Low_EB</code>. 
	 */
	public void setLowEb(java.lang.Double value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>sr25food.nut_data.Low_EB</code>. 
	 */
	public java.lang.Double getLowEb() {
		return (java.lang.Double) getValue(13);
	}

	/**
	 * Setter for <code>sr25food.nut_data.Up_EB</code>. 
	 */
	public void setUpEb(java.lang.Double value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>sr25food.nut_data.Up_EB</code>. 
	 */
	public java.lang.Double getUpEb() {
		return (java.lang.Double) getValue(14);
	}

	/**
	 * Setter for <code>sr25food.nut_data.Stat_Cmt</code>. 
	 */
	public void setStatCmt(java.lang.String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>sr25food.nut_data.Stat_Cmt</code>. 
	 */
	public java.lang.String getStatCmt() {
		return (java.lang.String) getValue(15);
	}

	/**
	 * Setter for <code>sr25food.nut_data.AddMod_Date</code>. 
	 */
	public void setAddmodDate(java.lang.String value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>sr25food.nut_data.AddMod_Date</code>. 
	 */
	public java.lang.String getAddmodDate() {
		return (java.lang.String) getValue(16);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.String, java.lang.String> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record17 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row17<java.lang.String, java.lang.String, java.lang.Double, java.lang.Integer, java.lang.Double, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row17) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row17<java.lang.String, java.lang.String, java.lang.Double, java.lang.Integer, java.lang.Double, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row17) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return assets.sr25food.tables.NutData.NUT_DATA.NDB_NO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return assets.sr25food.tables.NutData.NUT_DATA.NUTR_NO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field3() {
		return assets.sr25food.tables.NutData.NUT_DATA.NUTR_VAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return assets.sr25food.tables.NutData.NUT_DATA.NUM_DATA_PTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field5() {
		return assets.sr25food.tables.NutData.NUT_DATA.STD_ERROR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return assets.sr25food.tables.NutData.NUT_DATA.SRC_CD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return assets.sr25food.tables.NutData.NUT_DATA.DERIV_CD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return assets.sr25food.tables.NutData.NUT_DATA.REF_NDB_NO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return assets.sr25food.tables.NutData.NUT_DATA.ADD_NUTR_MARK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field10() {
		return assets.sr25food.tables.NutData.NUT_DATA.NUM_STUDIES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field11() {
		return assets.sr25food.tables.NutData.NUT_DATA.MIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field12() {
		return assets.sr25food.tables.NutData.NUT_DATA.MAX;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field13() {
		return assets.sr25food.tables.NutData.NUT_DATA.DF;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field14() {
		return assets.sr25food.tables.NutData.NUT_DATA.LOW_EB;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field15() {
		return assets.sr25food.tables.NutData.NUT_DATA.UP_EB;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field16() {
		return assets.sr25food.tables.NutData.NUT_DATA.STAT_CMT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field17() {
		return assets.sr25food.tables.NutData.NUT_DATA.ADDMOD_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getNdbNo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getNutrNo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value3() {
		return getNutrVal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getNumDataPts();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value5() {
		return getStdError();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getSrcCd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getDerivCd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getRefNdbNo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getAddNutrMark();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value10() {
		return getNumStudies();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value11() {
		return getMin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value12() {
		return getMax();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value13() {
		return getDf();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value14() {
		return getLowEb();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value15() {
		return getUpEb();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value16() {
		return getStatCmt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value17() {
		return getAddmodDate();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached NutDataRecord
	 */
	public NutDataRecord() {
		super(assets.sr25food.tables.NutData.NUT_DATA);
	}
}
