/**
 * This class is generated by jOOQ
 */
package assets.sr25food.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Abbrev extends org.jooq.impl.TableImpl<assets.sr25food.tables.records.AbbrevRecord> {

	private static final long serialVersionUID = -1327677779;

	/**
	 * The singleton instance of <code>sr25food.abbrev</code>
	 */
	public static final assets.sr25food.tables.Abbrev ABBREV = new assets.sr25food.tables.Abbrev();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<assets.sr25food.tables.records.AbbrevRecord> getRecordType() {
		return assets.sr25food.tables.records.AbbrevRecord.class;
	}

	/**
	 * The column <code>sr25food.abbrev.NDB_No</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.String> NDB_NO = createField("NDB_No", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sr25food.abbrev.Shrt_Desc</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.String> SHRT_DESC = createField("Shrt_Desc", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sr25food.abbrev.Water_(g)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> WATER__G_ = createField("Water_(g)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Energ_Kcal</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> ENERG_KCAL = createField("Energ_Kcal", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Protein_(g)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> PROTEIN__G_ = createField("Protein_(g)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Lipid_Tot_(g)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> LIPID_TOT__G_ = createField("Lipid_Tot_(g)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Ash_(g)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> ASH__G_ = createField("Ash_(g)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Carbohydrt_(g)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> CARBOHYDRT__G_ = createField("Carbohydrt_(g)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Fiber_TD_(g)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> FIBER_TD__G_ = createField("Fiber_TD_(g)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Sugar_Tot_(g)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> SUGAR_TOT__G_ = createField("Sugar_Tot_(g)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Calcium_(mg)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> CALCIUM__MG_ = createField("Calcium_(mg)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Iron_(mg)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> IRON__MG_ = createField("Iron_(mg)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Magnesium_(mg)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> MAGNESIUM__MG_ = createField("Magnesium_(mg)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Phosphorus_(mg)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> PHOSPHORUS__MG_ = createField("Phosphorus_(mg)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Potassium_(mg)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> POTASSIUM__MG_ = createField("Potassium_(mg)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Sodium_(mg)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> SODIUM__MG_ = createField("Sodium_(mg)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Zinc_(mg)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> ZINC__MG_ = createField("Zinc_(mg)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Copper_mg)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> COPPER_MG_ = createField("Copper_mg)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Manganese_(mg)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> MANGANESE__MG_ = createField("Manganese_(mg)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Selenium_(ug)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> SELENIUM__UG_ = createField("Selenium_(ug)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Vit_C_(mg)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> VIT_C__MG_ = createField("Vit_C_(mg)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Thiamin_(mg)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> THIAMIN__MG_ = createField("Thiamin_(mg)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Riboflavin_(mg)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> RIBOFLAVIN__MG_ = createField("Riboflavin_(mg)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Niacin_(mg)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> NIACIN__MG_ = createField("Niacin_(mg)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Panto_Acid_mg)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> PANTO_ACID_MG_ = createField("Panto_Acid_mg)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Vit_B6_(mg)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> VIT_B6__MG_ = createField("Vit_B6_(mg)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Folate_Tot_(ug)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> FOLATE_TOT__UG_ = createField("Folate_Tot_(ug)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Folic_Acid_(ug)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> FOLIC_ACID__UG_ = createField("Folic_Acid_(ug)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Food_Folate_(ug)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> FOOD_FOLATE__UG_ = createField("Food_Folate_(ug)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Folate_DFE_(ug)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> FOLATE_DFE__UG_ = createField("Folate_DFE_(ug)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Choline_Tot_ (mg)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> CHOLINE_TOT___MG_ = createField("Choline_Tot_ (mg)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Vit_B12_(ug)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> VIT_B12__UG_ = createField("Vit_B12_(ug)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Vit_A_IU</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> VIT_A_IU = createField("Vit_A_IU", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Vit_A_RAE</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> VIT_A_RAE = createField("Vit_A_RAE", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Retinol_(ug)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> RETINOL__UG_ = createField("Retinol_(ug)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Alpha_Carot_(ug)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> ALPHA_CAROT__UG_ = createField("Alpha_Carot_(ug)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Beta_Carot_(ug)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> BETA_CAROT__UG_ = createField("Beta_Carot_(ug)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Beta_Crypt_(ug)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> BETA_CRYPT__UG_ = createField("Beta_Crypt_(ug)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Lycopene_(ug)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> LYCOPENE__UG_ = createField("Lycopene_(ug)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Lut+Zea_ (ug)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> LUT_ZEA___UG_ = createField("Lut+Zea_ (ug)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Vit_E_(mg)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> VIT_E__MG_ = createField("Vit_E_(mg)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Vit_D_ (ug)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> VIT_D___UG_ = createField("Vit_D_ (ug)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.ViVit_D_IU</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> VIVIT_D_IU = createField("ViVit_D_IU", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Vit_K_ (ug)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> VIT_K___UG_ = createField("Vit_K_ (ug)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.FA_Sat_(g)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> FA_SAT__G_ = createField("FA_Sat_(g)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.FA_Mono_(g)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> FA_MONO__G_ = createField("FA_Mono_(g)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.FA_Poly_(g)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> FA_POLY__G_ = createField("FA_Poly_(g)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.Cholestrl_(mg)</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> CHOLESTRL__MG_ = createField("Cholestrl_(mg)", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.GmWt_1</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> GMWT_1 = createField("GmWt_1", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.GmWt_Desc1</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.String> GMWT_DESC1 = createField("GmWt_Desc1", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sr25food.abbrev.GmWt_2</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> GMWT_2 = createField("GmWt_2", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.abbrev.GmWt_Desc2</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.String> GMWT_DESC2 = createField("GmWt_Desc2", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sr25food.abbrev.Refuse_Pct</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.AbbrevRecord, java.lang.Double> REFUSE_PCT = createField("Refuse_Pct", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * Create a <code>sr25food.abbrev</code> table reference
	 */
	public Abbrev() {
		super("abbrev", assets.sr25food.Sr25food.SR25FOOD);
	}

	/**
	 * Create an aliased <code>sr25food.abbrev</code> table reference
	 */
	public Abbrev(java.lang.String alias) {
		super(alias, assets.sr25food.Sr25food.SR25FOOD, assets.sr25food.tables.Abbrev.ABBREV);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<assets.sr25food.tables.records.AbbrevRecord> getPrimaryKey() {
		return assets.sr25food.Keys.KEY_ABBREV_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<assets.sr25food.tables.records.AbbrevRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<assets.sr25food.tables.records.AbbrevRecord>>asList(assets.sr25food.Keys.KEY_ABBREV_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public assets.sr25food.tables.Abbrev as(java.lang.String alias) {
		return new assets.sr25food.tables.Abbrev(alias);
	}
}
