/**
 * This class is generated by jOOQ
 */
package assets.sr25food.tables;

/**
 * This class is generated by jOOQ.
 *
 * VIEW
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Allfoodsummary extends org.jooq.impl.TableImpl<assets.sr25food.tables.records.AllfoodsummaryRecord> {

	private static final long serialVersionUID = 1603129181;

	/**
	 * The singleton instance of <code>sr25food.allfoodsummary</code>
	 */
	public static final assets.sr25food.tables.Allfoodsummary ALLFOODSUMMARY = new assets.sr25food.tables.Allfoodsummary();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<assets.sr25food.tables.records.AllfoodsummaryRecord> getRecordType() {
		return assets.sr25food.tables.records.AllfoodsummaryRecord.class;
	}

	/**
	 * Create a <code>sr25food.allfoodsummary</code> table reference
	 */
	public Allfoodsummary() {
		super("allfoodsummary", assets.sr25food.Sr25food.SR25FOOD);
	}

	/**
	 * Create an aliased <code>sr25food.allfoodsummary</code> table reference
	 */
	public Allfoodsummary(java.lang.String alias) {
		super(alias, assets.sr25food.Sr25food.SR25FOOD, assets.sr25food.tables.Allfoodsummary.ALLFOODSUMMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public assets.sr25food.tables.Allfoodsummary as(java.lang.String alias) {
		return new assets.sr25food.tables.Allfoodsummary(alias);
	}
}
