/**
 * This class is generated by jOOQ
 */
package assets.sr25food.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataSrc extends org.jooq.impl.TableImpl<assets.sr25food.tables.records.DataSrcRecord> {

	private static final long serialVersionUID = 1073866214;

	/**
	 * The singleton instance of <code>sr25food.data_src</code>
	 */
	public static final assets.sr25food.tables.DataSrc DATA_SRC = new assets.sr25food.tables.DataSrc();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<assets.sr25food.tables.records.DataSrcRecord> getRecordType() {
		return assets.sr25food.tables.records.DataSrcRecord.class;
	}

	/**
	 * The column <code>sr25food.data_src.DataSrc_ID</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.DataSrcRecord, java.lang.String> DATASRC_ID = createField("DataSrc_ID", org.jooq.impl.SQLDataType.VARCHAR.length(6), this);

	/**
	 * The column <code>sr25food.data_src.Authors</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.DataSrcRecord, java.lang.String> AUTHORS = createField("Authors", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sr25food.data_src.Title</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.DataSrcRecord, java.lang.String> TITLE = createField("Title", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sr25food.data_src.Year</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.DataSrcRecord, java.lang.String> YEAR = createField("Year", org.jooq.impl.SQLDataType.VARCHAR.length(4), this);

	/**
	 * The column <code>sr25food.data_src.Journal</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.DataSrcRecord, java.lang.String> JOURNAL = createField("Journal", org.jooq.impl.SQLDataType.VARCHAR.length(135), this);

	/**
	 * The column <code>sr25food.data_src.Vol_City</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.DataSrcRecord, java.lang.String> VOL_CITY = createField("Vol_City", org.jooq.impl.SQLDataType.VARCHAR.length(16), this);

	/**
	 * The column <code>sr25food.data_src.Issue_State</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.DataSrcRecord, java.lang.String> ISSUE_STATE = createField("Issue_State", org.jooq.impl.SQLDataType.VARCHAR.length(5), this);

	/**
	 * The column <code>sr25food.data_src.Start_Page</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.DataSrcRecord, java.lang.String> START_PAGE = createField("Start_Page", org.jooq.impl.SQLDataType.VARCHAR.length(5), this);

	/**
	 * The column <code>sr25food.data_src.End_Page</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.DataSrcRecord, java.lang.String> END_PAGE = createField("End_Page", org.jooq.impl.SQLDataType.VARCHAR.length(5), this);

	/**
	 * Create a <code>sr25food.data_src</code> table reference
	 */
	public DataSrc() {
		super("data_src", assets.sr25food.Sr25food.SR25FOOD);
	}

	/**
	 * Create an aliased <code>sr25food.data_src</code> table reference
	 */
	public DataSrc(java.lang.String alias) {
		super(alias, assets.sr25food.Sr25food.SR25FOOD, assets.sr25food.tables.DataSrc.DATA_SRC);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<assets.sr25food.tables.records.DataSrcRecord> getPrimaryKey() {
		return assets.sr25food.Keys.KEY_DATA_SRC_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<assets.sr25food.tables.records.DataSrcRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<assets.sr25food.tables.records.DataSrcRecord>>asList(assets.sr25food.Keys.KEY_DATA_SRC_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public assets.sr25food.tables.DataSrc as(java.lang.String alias) {
		return new assets.sr25food.tables.DataSrc(alias);
	}
}
