/**
 * This class is generated by jOOQ
 */
package assets.sr25food.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Datsrcln extends org.jooq.impl.TableImpl<assets.sr25food.tables.records.DatsrclnRecord> {

	private static final long serialVersionUID = -1610231738;

	/**
	 * The singleton instance of <code>sr25food.datsrcln</code>
	 */
	public static final assets.sr25food.tables.Datsrcln DATSRCLN = new assets.sr25food.tables.Datsrcln();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<assets.sr25food.tables.records.DatsrclnRecord> getRecordType() {
		return assets.sr25food.tables.records.DatsrclnRecord.class;
	}

	/**
	 * The column <code>sr25food.datsrcln.NDB_No</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.DatsrclnRecord, java.lang.String> NDB_NO = createField("NDB_No", org.jooq.impl.SQLDataType.VARCHAR.length(5), this);

	/**
	 * The column <code>sr25food.datsrcln.Nutr_No</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.DatsrclnRecord, java.lang.String> NUTR_NO = createField("Nutr_No", org.jooq.impl.SQLDataType.VARCHAR.length(3), this);

	/**
	 * The column <code>sr25food.datsrcln.DataSrc_ID</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.DatsrclnRecord, java.lang.String> DATASRC_ID = createField("DataSrc_ID", org.jooq.impl.SQLDataType.VARCHAR.length(6), this);

	/**
	 * Create a <code>sr25food.datsrcln</code> table reference
	 */
	public Datsrcln() {
		super("datsrcln", assets.sr25food.Sr25food.SR25FOOD);
	}

	/**
	 * Create an aliased <code>sr25food.datsrcln</code> table reference
	 */
	public Datsrcln(java.lang.String alias) {
		super(alias, assets.sr25food.Sr25food.SR25FOOD, assets.sr25food.tables.Datsrcln.DATSRCLN);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<assets.sr25food.tables.records.DatsrclnRecord> getPrimaryKey() {
		return assets.sr25food.Keys.KEY_DATSRCLN_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<assets.sr25food.tables.records.DatsrclnRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<assets.sr25food.tables.records.DatsrclnRecord>>asList(assets.sr25food.Keys.KEY_DATSRCLN_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public assets.sr25food.tables.Datsrcln as(java.lang.String alias) {
		return new assets.sr25food.tables.Datsrcln(alias);
	}
}
