/**
 * This class is generated by jOOQ
 */
package assets.sr25food.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DerivCd extends org.jooq.impl.TableImpl<assets.sr25food.tables.records.DerivCdRecord> {

	private static final long serialVersionUID = 870842413;

	/**
	 * The singleton instance of <code>sr25food.deriv_cd</code>
	 */
	public static final assets.sr25food.tables.DerivCd DERIV_CD = new assets.sr25food.tables.DerivCd();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<assets.sr25food.tables.records.DerivCdRecord> getRecordType() {
		return assets.sr25food.tables.records.DerivCdRecord.class;
	}

	/**
	 * The column <code>sr25food.deriv_cd.Deriv_CD</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.DerivCdRecord, java.lang.String> DERIV_CD_ = createField("Deriv_CD", org.jooq.impl.SQLDataType.VARCHAR.length(4), this);

	/**
	 * The column <code>sr25food.deriv_cd.Deriv_Desc</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.DerivCdRecord, java.lang.String> DERIV_DESC = createField("Deriv_Desc", org.jooq.impl.SQLDataType.VARCHAR.length(120), this);

	/**
	 * Create a <code>sr25food.deriv_cd</code> table reference
	 */
	public DerivCd() {
		super("deriv_cd", assets.sr25food.Sr25food.SR25FOOD);
	}

	/**
	 * Create an aliased <code>sr25food.deriv_cd</code> table reference
	 */
	public DerivCd(java.lang.String alias) {
		super(alias, assets.sr25food.Sr25food.SR25FOOD, assets.sr25food.tables.DerivCd.DERIV_CD);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<assets.sr25food.tables.records.DerivCdRecord> getPrimaryKey() {
		return assets.sr25food.Keys.KEY_DERIV_CD_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<assets.sr25food.tables.records.DerivCdRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<assets.sr25food.tables.records.DerivCdRecord>>asList(assets.sr25food.Keys.KEY_DERIV_CD_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public assets.sr25food.tables.DerivCd as(java.lang.String alias) {
		return new assets.sr25food.tables.DerivCd(alias);
	}
}
