/**
 * This class is generated by jOOQ
 */
package assets.sr25food.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FdGroup extends org.jooq.impl.TableImpl<assets.sr25food.tables.records.FdGroupRecord> {

	private static final long serialVersionUID = 870959332;

	/**
	 * The singleton instance of <code>sr25food.fd_group</code>
	 */
	public static final assets.sr25food.tables.FdGroup FD_GROUP = new assets.sr25food.tables.FdGroup();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<assets.sr25food.tables.records.FdGroupRecord> getRecordType() {
		return assets.sr25food.tables.records.FdGroupRecord.class;
	}

	/**
	 * The column <code>sr25food.fd_group.FdGrp_CD</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.FdGroupRecord, java.lang.String> FDGRP_CD = createField("FdGrp_CD", org.jooq.impl.SQLDataType.VARCHAR.length(5), this);

	/**
	 * The column <code>sr25food.fd_group.FdGrp_Desc</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.FdGroupRecord, java.lang.String> FDGRP_DESC = createField("FdGrp_Desc", org.jooq.impl.SQLDataType.VARCHAR.length(60), this);

	/**
	 * Create a <code>sr25food.fd_group</code> table reference
	 */
	public FdGroup() {
		super("fd_group", assets.sr25food.Sr25food.SR25FOOD);
	}

	/**
	 * Create an aliased <code>sr25food.fd_group</code> table reference
	 */
	public FdGroup(java.lang.String alias) {
		super(alias, assets.sr25food.Sr25food.SR25FOOD, assets.sr25food.tables.FdGroup.FD_GROUP);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<assets.sr25food.tables.records.FdGroupRecord> getPrimaryKey() {
		return assets.sr25food.Keys.KEY_FD_GROUP_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<assets.sr25food.tables.records.FdGroupRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<assets.sr25food.tables.records.FdGroupRecord>>asList(assets.sr25food.Keys.KEY_FD_GROUP_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public assets.sr25food.tables.FdGroup as(java.lang.String alias) {
		return new assets.sr25food.tables.FdGroup(alias);
	}
}
