/**
 * This class is generated by jOOQ
 */
package assets.sr25food.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FoodDes extends org.jooq.impl.TableImpl<assets.sr25food.tables.records.FoodDesRecord> {

	private static final long serialVersionUID = 1662210293;

	/**
	 * The singleton instance of <code>sr25food.food_des</code>
	 */
	public static final assets.sr25food.tables.FoodDes FOOD_DES = new assets.sr25food.tables.FoodDes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<assets.sr25food.tables.records.FoodDesRecord> getRecordType() {
		return assets.sr25food.tables.records.FoodDesRecord.class;
	}

	/**
	 * The column <code>sr25food.food_des.NDB_No</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.FoodDesRecord, java.lang.String> NDB_NO = createField("NDB_No", org.jooq.impl.SQLDataType.VARCHAR.length(5), this);

	/**
	 * The column <code>sr25food.food_des.FdGrp_Cd</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.FoodDesRecord, java.lang.String> FDGRP_CD = createField("FdGrp_Cd", org.jooq.impl.SQLDataType.VARCHAR.length(4), this);

	/**
	 * The column <code>sr25food.food_des.Long_Desc</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.FoodDesRecord, java.lang.String> LONG_DESC = createField("Long_Desc", org.jooq.impl.SQLDataType.VARCHAR.length(200), this);

	/**
	 * The column <code>sr25food.food_des.Shrt_Desc</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.FoodDesRecord, java.lang.String> SHRT_DESC = createField("Shrt_Desc", org.jooq.impl.SQLDataType.VARCHAR.length(60), this);

	/**
	 * The column <code>sr25food.food_des.ComName</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.FoodDesRecord, java.lang.String> COMNAME = createField("ComName", org.jooq.impl.SQLDataType.VARCHAR.length(100), this);

	/**
	 * The column <code>sr25food.food_des.ManufacName</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.FoodDesRecord, java.lang.String> MANUFACNAME = createField("ManufacName", org.jooq.impl.SQLDataType.VARCHAR.length(65), this);

	/**
	 * The column <code>sr25food.food_des.Survey</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.FoodDesRecord, java.lang.String> SURVEY = createField("Survey", org.jooq.impl.SQLDataType.VARCHAR.length(1), this);

	/**
	 * The column <code>sr25food.food_des.Ref_Desc</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.FoodDesRecord, java.lang.String> REF_DESC = createField("Ref_Desc", org.jooq.impl.SQLDataType.VARCHAR.length(135), this);

	/**
	 * The column <code>sr25food.food_des.Refuse</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.FoodDesRecord, java.lang.Integer> REFUSE = createField("Refuse", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sr25food.food_des.SciName</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.FoodDesRecord, java.lang.String> SCINAME = createField("SciName", org.jooq.impl.SQLDataType.VARCHAR.length(65), this);

	/**
	 * The column <code>sr25food.food_des.N_Factor</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.FoodDesRecord, java.lang.Double> N_FACTOR = createField("N_Factor", org.jooq.impl.SQLDataType.FLOAT, this);

	/**
	 * The column <code>sr25food.food_des.Pro_Factor</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.FoodDesRecord, java.lang.Double> PRO_FACTOR = createField("Pro_Factor", org.jooq.impl.SQLDataType.FLOAT, this);

	/**
	 * The column <code>sr25food.food_des.Fat_Factor</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.FoodDesRecord, java.lang.Double> FAT_FACTOR = createField("Fat_Factor", org.jooq.impl.SQLDataType.FLOAT, this);

	/**
	 * The column <code>sr25food.food_des.CHO_Factor</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.FoodDesRecord, java.lang.Double> CHO_FACTOR = createField("CHO_Factor", org.jooq.impl.SQLDataType.FLOAT, this);

	/**
	 * Create a <code>sr25food.food_des</code> table reference
	 */
	public FoodDes() {
		super("food_des", assets.sr25food.Sr25food.SR25FOOD);
	}

	/**
	 * Create an aliased <code>sr25food.food_des</code> table reference
	 */
	public FoodDes(java.lang.String alias) {
		super(alias, assets.sr25food.Sr25food.SR25FOOD, assets.sr25food.tables.FoodDes.FOOD_DES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<assets.sr25food.tables.records.FoodDesRecord> getPrimaryKey() {
		return assets.sr25food.Keys.KEY_FOOD_DES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<assets.sr25food.tables.records.FoodDesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<assets.sr25food.tables.records.FoodDesRecord>>asList(assets.sr25food.Keys.KEY_FOOD_DES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public assets.sr25food.tables.FoodDes as(java.lang.String alias) {
		return new assets.sr25food.tables.FoodDes(alias);
	}
}
