/**
 * This class is generated by jOOQ
 */
package assets.sr25food.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Langdesc extends org.jooq.impl.TableImpl<assets.sr25food.tables.records.LangdescRecord> {

	private static final long serialVersionUID = -431286491;

	/**
	 * The singleton instance of <code>sr25food.langdesc</code>
	 */
	public static final assets.sr25food.tables.Langdesc LANGDESC = new assets.sr25food.tables.Langdesc();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<assets.sr25food.tables.records.LangdescRecord> getRecordType() {
		return assets.sr25food.tables.records.LangdescRecord.class;
	}

	/**
	 * The column <code>sr25food.langdesc.Factor</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.LangdescRecord, java.lang.String> FACTOR = createField("Factor", org.jooq.impl.SQLDataType.VARCHAR.length(6), this);

	/**
	 * The column <code>sr25food.langdesc.Description</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.LangdescRecord, java.lang.String> DESCRIPTION = createField("Description", org.jooq.impl.SQLDataType.VARCHAR.length(250), this);

	/**
	 * Create a <code>sr25food.langdesc</code> table reference
	 */
	public Langdesc() {
		super("langdesc", assets.sr25food.Sr25food.SR25FOOD);
	}

	/**
	 * Create an aliased <code>sr25food.langdesc</code> table reference
	 */
	public Langdesc(java.lang.String alias) {
		super(alias, assets.sr25food.Sr25food.SR25FOOD, assets.sr25food.tables.Langdesc.LANGDESC);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<assets.sr25food.tables.records.LangdescRecord> getPrimaryKey() {
		return assets.sr25food.Keys.KEY_LANGDESC_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<assets.sr25food.tables.records.LangdescRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<assets.sr25food.tables.records.LangdescRecord>>asList(assets.sr25food.Keys.KEY_LANGDESC_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public assets.sr25food.tables.Langdesc as(java.lang.String alias) {
		return new assets.sr25food.tables.Langdesc(alias);
	}
}
