/**
 * This class is generated by jOOQ
 */
package assets.sr25food.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Langual extends org.jooq.impl.TableImpl<assets.sr25food.tables.records.LangualRecord> {

	private static final long serialVersionUID = -1803067211;

	/**
	 * The singleton instance of <code>sr25food.langual</code>
	 */
	public static final assets.sr25food.tables.Langual LANGUAL = new assets.sr25food.tables.Langual();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<assets.sr25food.tables.records.LangualRecord> getRecordType() {
		return assets.sr25food.tables.records.LangualRecord.class;
	}

	/**
	 * The column <code>sr25food.langual.NDB_No</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.LangualRecord, java.lang.String> NDB_NO = createField("NDB_No", org.jooq.impl.SQLDataType.VARCHAR.length(5), this);

	/**
	 * The column <code>sr25food.langual.Factor</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.LangualRecord, java.lang.String> FACTOR = createField("Factor", org.jooq.impl.SQLDataType.VARCHAR.length(6), this);

	/**
	 * Create a <code>sr25food.langual</code> table reference
	 */
	public Langual() {
		super("langual", assets.sr25food.Sr25food.SR25FOOD);
	}

	/**
	 * Create an aliased <code>sr25food.langual</code> table reference
	 */
	public Langual(java.lang.String alias) {
		super(alias, assets.sr25food.Sr25food.SR25FOOD, assets.sr25food.tables.Langual.LANGUAL);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<assets.sr25food.tables.records.LangualRecord> getPrimaryKey() {
		return assets.sr25food.Keys.KEY_LANGUAL_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<assets.sr25food.tables.records.LangualRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<assets.sr25food.tables.records.LangualRecord>>asList(assets.sr25food.Keys.KEY_LANGUAL_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public assets.sr25food.tables.Langual as(java.lang.String alias) {
		return new assets.sr25food.tables.Langual(alias);
	}
}
