/**
 * This class is generated by jOOQ
 */
package assets.sr25food.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NutData extends org.jooq.impl.TableImpl<assets.sr25food.tables.records.NutDataRecord> {

	private static final long serialVersionUID = -524343961;

	/**
	 * The singleton instance of <code>sr25food.nut_data</code>
	 */
	public static final assets.sr25food.tables.NutData NUT_DATA = new assets.sr25food.tables.NutData();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<assets.sr25food.tables.records.NutDataRecord> getRecordType() {
		return assets.sr25food.tables.records.NutDataRecord.class;
	}

	/**
	 * The column <code>sr25food.nut_data.NDB_No</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.NutDataRecord, java.lang.String> NDB_NO = createField("NDB_No", org.jooq.impl.SQLDataType.VARCHAR.length(5), this);

	/**
	 * The column <code>sr25food.nut_data.Nutr_No</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.NutDataRecord, java.lang.String> NUTR_NO = createField("Nutr_No", org.jooq.impl.SQLDataType.VARCHAR.length(3), this);

	/**
	 * The column <code>sr25food.nut_data.Nutr_Val</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.NutDataRecord, java.lang.Double> NUTR_VAL = createField("Nutr_Val", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.nut_data.Num_Data_Pts</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.NutDataRecord, java.lang.Integer> NUM_DATA_PTS = createField("Num_Data_Pts", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sr25food.nut_data.Std_Error</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.NutDataRecord, java.lang.Double> STD_ERROR = createField("Std_Error", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.nut_data.Src_Cd</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.NutDataRecord, java.lang.String> SRC_CD = createField("Src_Cd", org.jooq.impl.SQLDataType.VARCHAR.length(2), this);

	/**
	 * The column <code>sr25food.nut_data.Deriv_Cd</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.NutDataRecord, java.lang.String> DERIV_CD = createField("Deriv_Cd", org.jooq.impl.SQLDataType.VARCHAR.length(4), this);

	/**
	 * The column <code>sr25food.nut_data.Ref_NDB_No</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.NutDataRecord, java.lang.String> REF_NDB_NO = createField("Ref_NDB_No", org.jooq.impl.SQLDataType.VARCHAR.length(5), this);

	/**
	 * The column <code>sr25food.nut_data.Add_Nutr_Mark</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.NutDataRecord, java.lang.String> ADD_NUTR_MARK = createField("Add_Nutr_Mark", org.jooq.impl.SQLDataType.VARCHAR.length(1), this);

	/**
	 * The column <code>sr25food.nut_data.Num_Studies</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.NutDataRecord, java.lang.Integer> NUM_STUDIES = createField("Num_Studies", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sr25food.nut_data.Min</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.NutDataRecord, java.lang.Double> MIN = createField("Min", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.nut_data.Max</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.NutDataRecord, java.lang.Double> MAX = createField("Max", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.nut_data.DF</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.NutDataRecord, java.lang.Double> DF = createField("DF", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.nut_data.Low_EB</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.NutDataRecord, java.lang.Double> LOW_EB = createField("Low_EB", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.nut_data.Up_EB</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.NutDataRecord, java.lang.Double> UP_EB = createField("Up_EB", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.nut_data.Stat_Cmt</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.NutDataRecord, java.lang.String> STAT_CMT = createField("Stat_Cmt", org.jooq.impl.SQLDataType.VARCHAR.length(10), this);

	/**
	 * The column <code>sr25food.nut_data.AddMod_Date</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.NutDataRecord, java.lang.String> ADDMOD_DATE = createField("AddMod_Date", org.jooq.impl.SQLDataType.VARCHAR.length(10), this);

	/**
	 * Create a <code>sr25food.nut_data</code> table reference
	 */
	public NutData() {
		super("nut_data", assets.sr25food.Sr25food.SR25FOOD);
	}

	/**
	 * Create an aliased <code>sr25food.nut_data</code> table reference
	 */
	public NutData(java.lang.String alias) {
		super(alias, assets.sr25food.Sr25food.SR25FOOD, assets.sr25food.tables.NutData.NUT_DATA);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<assets.sr25food.tables.records.NutDataRecord> getPrimaryKey() {
		return assets.sr25food.Keys.KEY_NUT_DATA_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<assets.sr25food.tables.records.NutDataRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<assets.sr25food.tables.records.NutDataRecord>>asList(assets.sr25food.Keys.KEY_NUT_DATA_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public assets.sr25food.tables.NutData as(java.lang.String alias) {
		return new assets.sr25food.tables.NutData(alias);
	}
}
