/**
 * This class is generated by jOOQ
 */
package assets.sr25food.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NutrDef extends org.jooq.impl.TableImpl<assets.sr25food.tables.records.NutrDefRecord> {

	private static final long serialVersionUID = 641803974;

	/**
	 * The singleton instance of <code>sr25food.nutr_def</code>
	 */
	public static final assets.sr25food.tables.NutrDef NUTR_DEF = new assets.sr25food.tables.NutrDef();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<assets.sr25food.tables.records.NutrDefRecord> getRecordType() {
		return assets.sr25food.tables.records.NutrDefRecord.class;
	}

	/**
	 * The column <code>sr25food.nutr_def.Nutr_No</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.NutrDefRecord, java.lang.String> NUTR_NO = createField("Nutr_No", org.jooq.impl.SQLDataType.VARCHAR.length(3), this);

	/**
	 * The column <code>sr25food.nutr_def.Units</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.NutrDefRecord, java.lang.String> UNITS = createField("Units", org.jooq.impl.SQLDataType.VARCHAR.length(7), this);

	/**
	 * The column <code>sr25food.nutr_def.Tagname</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.NutrDefRecord, java.lang.String> TAGNAME = createField("Tagname", org.jooq.impl.SQLDataType.VARCHAR.length(20), this);

	/**
	 * The column <code>sr25food.nutr_def.NutrDesc</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.NutrDefRecord, java.lang.String> NUTRDESC = createField("NutrDesc", org.jooq.impl.SQLDataType.VARCHAR.length(60), this);

	/**
	 * The column <code>sr25food.nutr_def.Num_Dec</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.NutrDefRecord, java.lang.String> NUM_DEC = createField("Num_Dec", org.jooq.impl.SQLDataType.VARCHAR.length(1), this);

	/**
	 * The column <code>sr25food.nutr_def.SR_Order</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.NutrDefRecord, java.lang.Double> SR_ORDER = createField("SR_Order", org.jooq.impl.SQLDataType.FLOAT, this);

	/**
	 * Create a <code>sr25food.nutr_def</code> table reference
	 */
	public NutrDef() {
		super("nutr_def", assets.sr25food.Sr25food.SR25FOOD);
	}

	/**
	 * Create an aliased <code>sr25food.nutr_def</code> table reference
	 */
	public NutrDef(java.lang.String alias) {
		super(alias, assets.sr25food.Sr25food.SR25FOOD, assets.sr25food.tables.NutrDef.NUTR_DEF);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<assets.sr25food.tables.records.NutrDefRecord> getPrimaryKey() {
		return assets.sr25food.Keys.KEY_NUTR_DEF_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<assets.sr25food.tables.records.NutrDefRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<assets.sr25food.tables.records.NutrDefRecord>>asList(assets.sr25food.Keys.KEY_NUTR_DEF_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public assets.sr25food.tables.NutrDef as(java.lang.String alias) {
		return new assets.sr25food.tables.NutrDef(alias);
	}
}
