/**
 * This class is generated by jOOQ
 */
package assets.sr25food.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Weight extends org.jooq.impl.TableImpl<assets.sr25food.tables.records.WeightRecord> {

	private static final long serialVersionUID = -1998128841;

	/**
	 * The singleton instance of <code>sr25food.weight</code>
	 */
	public static final assets.sr25food.tables.Weight WEIGHT = new assets.sr25food.tables.Weight();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<assets.sr25food.tables.records.WeightRecord> getRecordType() {
		return assets.sr25food.tables.records.WeightRecord.class;
	}

	/**
	 * The column <code>sr25food.weight.NDB_No</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.WeightRecord, java.lang.String> NDB_NO = createField("NDB_No", org.jooq.impl.SQLDataType.VARCHAR.length(5), this);

	/**
	 * The column <code>sr25food.weight.Seq</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.WeightRecord, java.lang.String> SEQ = createField("Seq", org.jooq.impl.SQLDataType.VARCHAR.length(2), this);

	/**
	 * The column <code>sr25food.weight.Amount</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.WeightRecord, java.lang.Double> AMOUNT = createField("Amount", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.weight.Msre_Desc</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.WeightRecord, java.lang.String> MSRE_DESC = createField("Msre_Desc", org.jooq.impl.SQLDataType.VARCHAR.length(84), this);

	/**
	 * The column <code>sr25food.weight.Gm_Wgt</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.WeightRecord, java.lang.Double> GM_WGT = createField("Gm_Wgt", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sr25food.weight.Num_Data_Pts</code>. 
	 */
	public final org.jooq.TableField<assets.sr25food.tables.records.WeightRecord, java.lang.Integer> NUM_DATA_PTS = createField("Num_Data_Pts", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>sr25food.weight</code> table reference
	 */
	public Weight() {
		super("weight", assets.sr25food.Sr25food.SR25FOOD);
	}

	/**
	 * Create an aliased <code>sr25food.weight</code> table reference
	 */
	public Weight(java.lang.String alias) {
		super(alias, assets.sr25food.Sr25food.SR25FOOD, assets.sr25food.tables.Weight.WEIGHT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<assets.sr25food.tables.records.WeightRecord> getPrimaryKey() {
		return assets.sr25food.Keys.KEY_WEIGHT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<assets.sr25food.tables.records.WeightRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<assets.sr25food.tables.records.WeightRecord>>asList(assets.sr25food.Keys.KEY_WEIGHT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public assets.sr25food.tables.Weight as(java.lang.String alias) {
		return new assets.sr25food.tables.Weight(alias);
	}
}
