/**
 * This class is generated by jOOQ
 */
package assets.dietfix.enums;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum DietfixAnsAnsexpert implements org.jooq.EnumType {

	DIETITIAN("DIETITIAN"),

	FITNESS_INSTRUCTOR("FITNESS_INSTRUCTOR"),

	NUTRITIONIST("NUTRITIONIST"),

	;

	private final java.lang.String literal;

	private DietfixAnsAnsexpert(java.lang.String literal) {
		this.literal = literal;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String getName() {
		return "dietfix_ans_AnsExpert";
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String getLiteral() {
		return literal;
	}
}
