/**
 * This class is generated by jOOQ
 */
package assets.sr25food;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>sr25food</code> 
 * schema
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<assets.sr25food.tables.records.AbbrevRecord> KEY_ABBREV_PRIMARY = UniqueKeys0.KEY_ABBREV_PRIMARY;
	public static final org.jooq.UniqueKey<assets.sr25food.tables.records.DataSrcRecord> KEY_DATA_SRC_PRIMARY = UniqueKeys0.KEY_DATA_SRC_PRIMARY;
	public static final org.jooq.UniqueKey<assets.sr25food.tables.records.DatsrclnRecord> KEY_DATSRCLN_PRIMARY = UniqueKeys0.KEY_DATSRCLN_PRIMARY;
	public static final org.jooq.UniqueKey<assets.sr25food.tables.records.DerivCdRecord> KEY_DERIV_CD_PRIMARY = UniqueKeys0.KEY_DERIV_CD_PRIMARY;
	public static final org.jooq.UniqueKey<assets.sr25food.tables.records.FdGroupRecord> KEY_FD_GROUP_PRIMARY = UniqueKeys0.KEY_FD_GROUP_PRIMARY;
	public static final org.jooq.UniqueKey<assets.sr25food.tables.records.FoodDesRecord> KEY_FOOD_DES_PRIMARY = UniqueKeys0.KEY_FOOD_DES_PRIMARY;
	public static final org.jooq.UniqueKey<assets.sr25food.tables.records.LangdescRecord> KEY_LANGDESC_PRIMARY = UniqueKeys0.KEY_LANGDESC_PRIMARY;
	public static final org.jooq.UniqueKey<assets.sr25food.tables.records.LangualRecord> KEY_LANGUAL_PRIMARY = UniqueKeys0.KEY_LANGUAL_PRIMARY;
	public static final org.jooq.UniqueKey<assets.sr25food.tables.records.NutrDefRecord> KEY_NUTR_DEF_PRIMARY = UniqueKeys0.KEY_NUTR_DEF_PRIMARY;
	public static final org.jooq.UniqueKey<assets.sr25food.tables.records.NutDataRecord> KEY_NUT_DATA_PRIMARY = UniqueKeys0.KEY_NUT_DATA_PRIMARY;
	public static final org.jooq.UniqueKey<assets.sr25food.tables.records.SrcCdRecord> KEY_SRC_CD_PRIMARY = UniqueKeys0.KEY_SRC_CD_PRIMARY;
	public static final org.jooq.UniqueKey<assets.sr25food.tables.records.WeightRecord> KEY_WEIGHT_PRIMARY = UniqueKeys0.KEY_WEIGHT_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<assets.sr25food.tables.records.AbbrevRecord> KEY_ABBREV_PRIMARY = createUniqueKey(assets.sr25food.tables.Abbrev.ABBREV, assets.sr25food.tables.Abbrev.ABBREV.NDB_NO);
		public static final org.jooq.UniqueKey<assets.sr25food.tables.records.DataSrcRecord> KEY_DATA_SRC_PRIMARY = createUniqueKey(assets.sr25food.tables.DataSrc.DATA_SRC, assets.sr25food.tables.DataSrc.DATA_SRC.DATASRC_ID);
		public static final org.jooq.UniqueKey<assets.sr25food.tables.records.DatsrclnRecord> KEY_DATSRCLN_PRIMARY = createUniqueKey(assets.sr25food.tables.Datsrcln.DATSRCLN, assets.sr25food.tables.Datsrcln.DATSRCLN.NDB_NO, assets.sr25food.tables.Datsrcln.DATSRCLN.NUTR_NO, assets.sr25food.tables.Datsrcln.DATSRCLN.DATASRC_ID);
		public static final org.jooq.UniqueKey<assets.sr25food.tables.records.DerivCdRecord> KEY_DERIV_CD_PRIMARY = createUniqueKey(assets.sr25food.tables.DerivCd.DERIV_CD, assets.sr25food.tables.DerivCd.DERIV_CD.DERIV_CD_);
		public static final org.jooq.UniqueKey<assets.sr25food.tables.records.FdGroupRecord> KEY_FD_GROUP_PRIMARY = createUniqueKey(assets.sr25food.tables.FdGroup.FD_GROUP, assets.sr25food.tables.FdGroup.FD_GROUP.FDGRP_CD);
		public static final org.jooq.UniqueKey<assets.sr25food.tables.records.FoodDesRecord> KEY_FOOD_DES_PRIMARY = createUniqueKey(assets.sr25food.tables.FoodDes.FOOD_DES, assets.sr25food.tables.FoodDes.FOOD_DES.NDB_NO);
		public static final org.jooq.UniqueKey<assets.sr25food.tables.records.LangdescRecord> KEY_LANGDESC_PRIMARY = createUniqueKey(assets.sr25food.tables.Langdesc.LANGDESC, assets.sr25food.tables.Langdesc.LANGDESC.FACTOR);
		public static final org.jooq.UniqueKey<assets.sr25food.tables.records.LangualRecord> KEY_LANGUAL_PRIMARY = createUniqueKey(assets.sr25food.tables.Langual.LANGUAL, assets.sr25food.tables.Langual.LANGUAL.NDB_NO, assets.sr25food.tables.Langual.LANGUAL.FACTOR);
		public static final org.jooq.UniqueKey<assets.sr25food.tables.records.NutrDefRecord> KEY_NUTR_DEF_PRIMARY = createUniqueKey(assets.sr25food.tables.NutrDef.NUTR_DEF, assets.sr25food.tables.NutrDef.NUTR_DEF.NUTR_NO);
		public static final org.jooq.UniqueKey<assets.sr25food.tables.records.NutDataRecord> KEY_NUT_DATA_PRIMARY = createUniqueKey(assets.sr25food.tables.NutData.NUT_DATA, assets.sr25food.tables.NutData.NUT_DATA.NDB_NO, assets.sr25food.tables.NutData.NUT_DATA.NUTR_NO);
		public static final org.jooq.UniqueKey<assets.sr25food.tables.records.SrcCdRecord> KEY_SRC_CD_PRIMARY = createUniqueKey(assets.sr25food.tables.SrcCd.SRC_CD, assets.sr25food.tables.SrcCd.SRC_CD.SRC_CD_);
		public static final org.jooq.UniqueKey<assets.sr25food.tables.records.WeightRecord> KEY_WEIGHT_PRIMARY = createUniqueKey(assets.sr25food.tables.Weight.WEIGHT, assets.sr25food.tables.Weight.WEIGHT.NDB_NO, assets.sr25food.tables.Weight.WEIGHT.SEQ);
	}
}
