/**
 * This class is generated by jOOQ
 */
package assets.sr25food;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sr25food extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -815835564;

	/**
	 * The singleton instance of <code>sr25food</code>
	 */
	public static final Sr25food SR25FOOD = new Sr25food();

	/**
	 * No further instances allowed
	 */
	private Sr25food() {
		super("sr25food");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			assets.sr25food.tables.Abbrev.ABBREV,
			assets.sr25food.tables.Allfoodsummary.ALLFOODSUMMARY,
			assets.sr25food.tables.DataSrc.DATA_SRC,
			assets.sr25food.tables.Datsrcln.DATSRCLN,
			assets.sr25food.tables.DerivCd.DERIV_CD,
			assets.sr25food.tables.FdGroup.FD_GROUP,
			assets.sr25food.tables.FoodDes.FOOD_DES,
			assets.sr25food.tables.Footnote.FOOTNOTE,
			assets.sr25food.tables.Langdesc.LANGDESC,
			assets.sr25food.tables.Langual.LANGUAL,
			assets.sr25food.tables.NutrDef.NUTR_DEF,
			assets.sr25food.tables.NutData.NUT_DATA,
			assets.sr25food.tables.SrcCd.SRC_CD,
			assets.sr25food.tables.Weight.WEIGHT);
	}
}
