/**
 * This class is generated by jOOQ
 */
package assets.sr25food;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in sr25food
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table sr25food.abbrev
	 */
	public static final assets.sr25food.tables.Abbrev ABBREV = assets.sr25food.tables.Abbrev.ABBREV;

	/**
	 * VIEW
	 */
	public static final assets.sr25food.tables.Allfoodsummary ALLFOODSUMMARY = assets.sr25food.tables.Allfoodsummary.ALLFOODSUMMARY;

	/**
	 * The table sr25food.data_src
	 */
	public static final assets.sr25food.tables.DataSrc DATA_SRC = assets.sr25food.tables.DataSrc.DATA_SRC;

	/**
	 * The table sr25food.datsrcln
	 */
	public static final assets.sr25food.tables.Datsrcln DATSRCLN = assets.sr25food.tables.Datsrcln.DATSRCLN;

	/**
	 * The table sr25food.deriv_cd
	 */
	public static final assets.sr25food.tables.DerivCd DERIV_CD = assets.sr25food.tables.DerivCd.DERIV_CD;

	/**
	 * The table sr25food.fd_group
	 */
	public static final assets.sr25food.tables.FdGroup FD_GROUP = assets.sr25food.tables.FdGroup.FD_GROUP;

	/**
	 * The table sr25food.food_des
	 */
	public static final assets.sr25food.tables.FoodDes FOOD_DES = assets.sr25food.tables.FoodDes.FOOD_DES;

	/**
	 * The table sr25food.footnote
	 */
	public static final assets.sr25food.tables.Footnote FOOTNOTE = assets.sr25food.tables.Footnote.FOOTNOTE;

	/**
	 * The table sr25food.langdesc
	 */
	public static final assets.sr25food.tables.Langdesc LANGDESC = assets.sr25food.tables.Langdesc.LANGDESC;

	/**
	 * The table sr25food.langual
	 */
	public static final assets.sr25food.tables.Langual LANGUAL = assets.sr25food.tables.Langual.LANGUAL;

	/**
	 * The table sr25food.nutr_def
	 */
	public static final assets.sr25food.tables.NutrDef NUTR_DEF = assets.sr25food.tables.NutrDef.NUTR_DEF;

	/**
	 * The table sr25food.nut_data
	 */
	public static final assets.sr25food.tables.NutData NUT_DATA = assets.sr25food.tables.NutData.NUT_DATA;

	/**
	 * The table sr25food.src_cd
	 */
	public static final assets.sr25food.tables.SrcCd SRC_CD = assets.sr25food.tables.SrcCd.SRC_CD;

	/**
	 * The table sr25food.weight
	 */
	public static final assets.sr25food.tables.Weight WEIGHT = assets.sr25food.tables.Weight.WEIGHT;
}
