/**
 * This class is generated by jOOQ
 */
package assets.dietfix.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DietfixAns extends org.jooq.impl.TableImpl<assets.dietfix.tables.records.DietfixAnsRecord> {

	private static final long serialVersionUID = 412947018;

	/**
	 * The singleton instance of <code>dietfix.dietfix_ans</code>
	 */
	public static final assets.dietfix.tables.DietfixAns DIETFIX_ANS = new assets.dietfix.tables.DietfixAns();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<assets.dietfix.tables.records.DietfixAnsRecord> getRecordType() {
		return assets.dietfix.tables.records.DietfixAnsRecord.class;
	}

	/**
	 * The column <code>dietfix.dietfix_ans.AnsID</code>. 
	 */
	public final org.jooq.TableField<assets.dietfix.tables.records.DietfixAnsRecord, java.lang.Integer> ANSID = createField("AnsID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>dietfix.dietfix_ans.AnsObj</code>. 
	 */
	public final org.jooq.TableField<assets.dietfix.tables.records.DietfixAnsRecord, byte[]> ANSOBJ = createField("AnsObj", org.jooq.impl.SQLDataType.BLOB.length(65535), this);

	/**
	 * The column <code>dietfix.dietfix_ans.AnsExpert</code>. 
	 */
	public final org.jooq.TableField<assets.dietfix.tables.records.DietfixAnsRecord, assets.dietfix.enums.DietfixAnsAnsexpert> ANSEXPERT = createField("AnsExpert", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(assets.dietfix.enums.DietfixAnsAnsexpert.class), this);

	/**
	 * The column <code>dietfix.dietfix_ans.AnsDesc</code>. 
	 */
	public final org.jooq.TableField<assets.dietfix.tables.records.DietfixAnsRecord, java.lang.String> ANSDESC = createField("AnsDesc", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>dietfix.dietfix_ans</code> table reference
	 */
	public DietfixAns() {
		super("dietfix_ans", assets.dietfix.Dietfix.DIETFIX);
	}

	/**
	 * Create an aliased <code>dietfix.dietfix_ans</code> table reference
	 */
	public DietfixAns(java.lang.String alias) {
		super(alias, assets.dietfix.Dietfix.DIETFIX, assets.dietfix.tables.DietfixAns.DIETFIX_ANS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<assets.dietfix.tables.records.DietfixAnsRecord, java.lang.Integer> getIdentity() {
		return assets.dietfix.Keys.IDENTITY_DIETFIX_ANS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<assets.dietfix.tables.records.DietfixAnsRecord> getPrimaryKey() {
		return assets.dietfix.Keys.KEY_DIETFIX_ANS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<assets.dietfix.tables.records.DietfixAnsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<assets.dietfix.tables.records.DietfixAnsRecord>>asList(assets.dietfix.Keys.KEY_DIETFIX_ANS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public assets.dietfix.tables.DietfixAns as(java.lang.String alias) {
		return new assets.dietfix.tables.DietfixAns(alias);
	}
}
