/**
 * This class is generated by jOOQ
 */
package assets.dietfix.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KnownWords extends org.jooq.impl.TableImpl<assets.dietfix.tables.records.KnownWordsRecord> {

	private static final long serialVersionUID = 142069367;

	/**
	 * The singleton instance of <code>dietfix.known_words</code>
	 */
	public static final assets.dietfix.tables.KnownWords KNOWN_WORDS = new assets.dietfix.tables.KnownWords();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<assets.dietfix.tables.records.KnownWordsRecord> getRecordType() {
		return assets.dietfix.tables.records.KnownWordsRecord.class;
	}

	/**
	 * The column <code>dietfix.known_words.id</code>. 
	 */
	public final org.jooq.TableField<assets.dietfix.tables.records.KnownWordsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>dietfix.known_words.word</code>. 
	 */
	public final org.jooq.TableField<assets.dietfix.tables.records.KnownWordsRecord, java.lang.String> WORD = createField("word", org.jooq.impl.SQLDataType.VARCHAR.length(100), this);

	/**
	 * The column <code>dietfix.known_words.pos_tag</code>. 
	 */
	public final org.jooq.TableField<assets.dietfix.tables.records.KnownWordsRecord, java.lang.String> POS_TAG = createField("pos_tag", org.jooq.impl.SQLDataType.VARCHAR.length(25), this);

	/**
	 * Create a <code>dietfix.known_words</code> table reference
	 */
	public KnownWords() {
		super("known_words", assets.dietfix.Dietfix.DIETFIX);
	}

	/**
	 * Create an aliased <code>dietfix.known_words</code> table reference
	 */
	public KnownWords(java.lang.String alias) {
		super(alias, assets.dietfix.Dietfix.DIETFIX, assets.dietfix.tables.KnownWords.KNOWN_WORDS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<assets.dietfix.tables.records.KnownWordsRecord, java.lang.Integer> getIdentity() {
		return assets.dietfix.Keys.IDENTITY_KNOWN_WORDS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<assets.dietfix.tables.records.KnownWordsRecord> getPrimaryKey() {
		return assets.dietfix.Keys.KEY_KNOWN_WORDS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<assets.dietfix.tables.records.KnownWordsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<assets.dietfix.tables.records.KnownWordsRecord>>asList(assets.dietfix.Keys.KEY_KNOWN_WORDS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public assets.dietfix.tables.KnownWords as(java.lang.String alias) {
		return new assets.dietfix.tables.KnownWords(alias);
	}
}
