/**
 * This class is generated by jOOQ
 */
package assets.dietfix.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserHistory extends org.jooq.impl.TableImpl<assets.dietfix.tables.records.UserHistoryRecord> {

	private static final long serialVersionUID = 895990439;

	/**
	 * The singleton instance of <code>dietfix.user_history</code>
	 */
	public static final assets.dietfix.tables.UserHistory USER_HISTORY = new assets.dietfix.tables.UserHistory();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<assets.dietfix.tables.records.UserHistoryRecord> getRecordType() {
		return assets.dietfix.tables.records.UserHistoryRecord.class;
	}

	/**
	 * The column <code>dietfix.user_history.historyBackgroundID</code>. 
	 */
	public final org.jooq.TableField<assets.dietfix.tables.records.UserHistoryRecord, java.lang.Integer> HISTORYBACKGROUNDID = createField("historyBackgroundID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>dietfix.user_history.hasAsthma</code>. 
	 */
	public final org.jooq.TableField<assets.dietfix.tables.records.UserHistoryRecord, java.lang.Byte> HASASTHMA = createField("hasAsthma", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The column <code>dietfix.user_history.hasDiebetes</code>. 
	 */
	public final org.jooq.TableField<assets.dietfix.tables.records.UserHistoryRecord, java.lang.Byte> HASDIEBETES = createField("hasDiebetes", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The column <code>dietfix.user_history.hasSeaFoodAllergy</code>. 
	 */
	public final org.jooq.TableField<assets.dietfix.tables.records.UserHistoryRecord, java.lang.Byte> HASSEAFOODALLERGY = createField("hasSeaFoodAllergy", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The column <code>dietfix.user_history.hasChickenAllergy</code>. 
	 */
	public final org.jooq.TableField<assets.dietfix.tables.records.UserHistoryRecord, java.lang.Byte> HASCHICKENALLERGY = createField("hasChickenAllergy", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The column <code>dietfix.user_history.hasPorkAllergy</code>. 
	 */
	public final org.jooq.TableField<assets.dietfix.tables.records.UserHistoryRecord, java.lang.Byte> HASPORKALLERGY = createField("hasPorkAllergy", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The column <code>dietfix.user_history.hasVeggieAllergy</code>. 
	 */
	public final org.jooq.TableField<assets.dietfix.tables.records.UserHistoryRecord, java.lang.Byte> HASVEGGIEALLERGY = createField("hasVeggieAllergy", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The column <code>dietfix.user_history.hasAlcoholAllergy</code>. 
	 */
	public final org.jooq.TableField<assets.dietfix.tables.records.UserHistoryRecord, java.lang.Byte> HASALCOHOLALLERGY = createField("hasAlcoholAllergy", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The column <code>dietfix.user_history.hasHeartProblem</code>. 
	 */
	public final org.jooq.TableField<assets.dietfix.tables.records.UserHistoryRecord, java.lang.Byte> HASHEARTPROBLEM = createField("hasHeartProblem", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * Create a <code>dietfix.user_history</code> table reference
	 */
	public UserHistory() {
		super("user_history", assets.dietfix.Dietfix.DIETFIX);
	}

	/**
	 * Create an aliased <code>dietfix.user_history</code> table reference
	 */
	public UserHistory(java.lang.String alias) {
		super(alias, assets.dietfix.Dietfix.DIETFIX, assets.dietfix.tables.UserHistory.USER_HISTORY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<assets.dietfix.tables.records.UserHistoryRecord, java.lang.Integer> getIdentity() {
		return assets.dietfix.Keys.IDENTITY_USER_HISTORY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<assets.dietfix.tables.records.UserHistoryRecord> getPrimaryKey() {
		return assets.dietfix.Keys.KEY_USER_HISTORY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<assets.dietfix.tables.records.UserHistoryRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<assets.dietfix.tables.records.UserHistoryRecord>>asList(assets.dietfix.Keys.KEY_USER_HISTORY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public assets.dietfix.tables.UserHistory as(java.lang.String alias) {
		return new assets.dietfix.tables.UserHistory(alias);
	}
}
