/**
 * This class is generated by jOOQ
 */
package assets.dietfix.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User extends org.jooq.impl.TableImpl<assets.dietfix.tables.records.UserRecord> {

	private static final long serialVersionUID = 1856592664;

	/**
	 * The singleton instance of <code>dietfix.user</code>
	 */
	public static final assets.dietfix.tables.User USER = new assets.dietfix.tables.User();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<assets.dietfix.tables.records.UserRecord> getRecordType() {
		return assets.dietfix.tables.records.UserRecord.class;
	}

	/**
	 * The column <code>dietfix.user.userID</code>. 
	 */
	public final org.jooq.TableField<assets.dietfix.tables.records.UserRecord, java.lang.Integer> USERID = createField("userID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>dietfix.user.username</code>. 
	 */
	public final org.jooq.TableField<assets.dietfix.tables.records.UserRecord, java.lang.String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(50), this);

	/**
	 * The column <code>dietfix.user.password</code>. 
	 */
	public final org.jooq.TableField<assets.dietfix.tables.records.UserRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(125), this);

	/**
	 * The column <code>dietfix.user.salt</code>. 
	 */
	public final org.jooq.TableField<assets.dietfix.tables.records.UserRecord, java.lang.String> SALT = createField("salt", org.jooq.impl.SQLDataType.VARCHAR.length(125), this);

	/**
	 * The column <code>dietfix.user.first_name</code>. 
	 */
	public final org.jooq.TableField<assets.dietfix.tables.records.UserRecord, java.lang.String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this);

	/**
	 * The column <code>dietfix.user.middle_name</code>. 
	 */
	public final org.jooq.TableField<assets.dietfix.tables.records.UserRecord, java.lang.String> MIDDLE_NAME = createField("middle_name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this);

	/**
	 * The column <code>dietfix.user.last_name</code>. 
	 */
	public final org.jooq.TableField<assets.dietfix.tables.records.UserRecord, java.lang.String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this);

	/**
	 * The column <code>dietfix.user.date_created</code>. 
	 */
	public final org.jooq.TableField<assets.dietfix.tables.records.UserRecord, java.sql.Date> DATE_CREATED = createField("date_created", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * The column <code>dietfix.user.date_modified</code>. 
	 */
	public final org.jooq.TableField<assets.dietfix.tables.records.UserRecord, java.sql.Date> DATE_MODIFIED = createField("date_modified", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * Create a <code>dietfix.user</code> table reference
	 */
	public User() {
		super("user", assets.dietfix.Dietfix.DIETFIX);
	}

	/**
	 * Create an aliased <code>dietfix.user</code> table reference
	 */
	public User(java.lang.String alias) {
		super(alias, assets.dietfix.Dietfix.DIETFIX, assets.dietfix.tables.User.USER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<assets.dietfix.tables.records.UserRecord, java.lang.Integer> getIdentity() {
		return assets.dietfix.Keys.IDENTITY_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<assets.dietfix.tables.records.UserRecord> getPrimaryKey() {
		return assets.dietfix.Keys.KEY_USER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<assets.dietfix.tables.records.UserRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<assets.dietfix.tables.records.UserRecord>>asList(assets.dietfix.Keys.KEY_USER_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public assets.dietfix.tables.User as(java.lang.String alias) {
		return new assets.dietfix.tables.User(alias);
	}
}
